import type { DevTerm } from './types'

export const devTerms = [
  {
    id: 'context',
    term: 'Context',
    pronunciation: '컨텍스트',
    koreanMeaning: '현재 판단에 필요한 배경 정보와 주변 조건',
    simpleMeaning: 'AI가 요청을 제대로 이해하도록 붙여 주는 상황 설명입니다.',
    joovisUsage: '이 학습 앱에서는 현재 폴더, 사용자 요청, 용어 데이터가 context입니다.',
    checkQuestion: '지금 판단에 꼭 필요한 배경은 무엇인가요?',
    codexPromptExample: 'Context는 독립형 학습 PWA입니다. 다른 JOOVIS 저장소는 보지 마세요.',
    category: 'AI Command',
  },
  {
    id: 'scope',
    term: 'Scope',
    pronunciation: '스코프',
    koreanMeaning: '작업에 포함되는 범위와 제외되는 범위',
    simpleMeaning: '무엇을 하고 무엇을 하지 않을지 정한 선입니다.',
    joovisUsage: '이 앱의 scope는 정적 용어 학습 UI와 로컬 저장 기능입니다.',
    checkQuestion: '이번 작업에서 명시적으로 제외해야 하는 것은 무엇인가요?',
    codexPromptExample: 'Scope를 현재 폴더의 static PWA로 제한하고 백엔드는 만들지 마세요.',
    category: 'Boundary / Safety',
  },
  {
    id: 'boundary',
    term: 'Boundary',
    pronunciation: '바운더리',
    koreanMeaning: '넘어가면 안 되는 시스템, 파일, 책임의 경계',
    simpleMeaning: '안전하게 작업하기 위한 울타리입니다.',
    joovisUsage: 'JOOVIS Terms Cockpit은 다른 JOOVIS 프로젝트와 분리된 boundary 안에서 동작합니다.',
    checkQuestion: '이 작업이 넘어가면 안 되는 경계는 어디인가요?',
    codexPromptExample: 'Boundary를 C:\\dev\\joovis-terms-cockpit 안으로 제한해 주세요.',
    category: 'Boundary / Safety',
  },
  {
    id: 'source-of-truth',
    term: 'Source of Truth',
    pronunciation: '소스 오브 트루스',
    koreanMeaning: '여러 정보 중 최종 기준이 되는 단일 원천',
    simpleMeaning: '헷갈릴 때 믿고 따르는 기준 데이터입니다.',
    joovisUsage: '용어 설명의 source of truth는 src/devTerms.ts입니다.',
    checkQuestion: '충돌하는 정보가 있을 때 무엇을 최종 기준으로 삼나요?',
    codexPromptExample: '용어 목록의 source of truth를 src/devTerms.ts로 두고 UI는 이 데이터만 읽게 하세요.',
    category: 'Data / Schema',
  },
  {
    id: 'capability-state',
    term: 'Capability State',
    pronunciation: '케이퍼빌리티 스테이트',
    koreanMeaning: '현재 사용할 수 있는 기능과 제한의 상태',
    simpleMeaning: '지금 가능한 일과 불가능한 일을 나타냅니다.',
    joovisUsage: '이 앱의 capability state는 React, Vite, TypeScript, PWA, localStorage입니다.',
    checkQuestion: '현재 환경에서 가능한 기능과 금지된 기능은 무엇인가요?',
    codexPromptExample: 'Capability state를 확인하고 외부 연동 없이 구현 가능한 방식만 사용하세요.',
    category: 'AI Command',
  },
  {
    id: 'contract',
    term: 'Contract',
    pronunciation: '컨트랙트',
    koreanMeaning: '모듈이나 데이터가 반드시 지켜야 하는 약속',
    simpleMeaning: '입력과 출력의 형태를 약속하는 규칙입니다.',
    joovisUsage: 'DevTerm 타입은 모든 용어 카드가 지켜야 하는 contract입니다.',
    checkQuestion: '이 데이터나 함수가 반드시 보장해야 하는 약속은 무엇인가요?',
    codexPromptExample: 'DevTerm contract를 깨지 말고 모든 항목이 같은 필드를 갖게 해 주세요.',
    category: 'Architecture',
  },
  {
    id: 'interface',
    term: 'Interface',
    pronunciation: '인터페이스',
    koreanMeaning: '두 부분이 서로 만나는 접점과 사용 방법',
    simpleMeaning: '서로 다른 코드가 대화하는 표면입니다.',
    joovisUsage: 'TermCard props는 카드 컴포넌트와 앱 상태가 만나는 interface입니다.',
    checkQuestion: '이 컴포넌트나 함수는 어떤 값으로 연결되나요?',
    codexPromptExample: 'TermCard interface를 작게 유지하고 필요한 props만 전달해 주세요.',
    category: 'Architecture',
  },
  {
    id: 'schema',
    term: 'Schema',
    pronunciation: '스키마',
    koreanMeaning: '데이터가 가져야 하는 구조와 필드 정의',
    simpleMeaning: '데이터의 모양을 정해 둔 설계도입니다.',
    joovisUsage: '용어 schema는 id, term, pronunciation, koreanMeaning 등으로 고정됩니다.',
    checkQuestion: '필수 필드가 빠지면 어떤 화면이 깨질까요?',
    codexPromptExample: 'Schema에 맞지 않는 용어 항목이 있는지 TypeScript로 확인해 주세요.',
    category: 'Data / Schema',
  },
  {
    id: 'artifact',
    term: 'Artifact',
    pronunciation: '아티팩트',
    koreanMeaning: '작업 결과로 남는 파일, 빌드 산출물, 문서',
    simpleMeaning: '만들어 낸 결과물입니다.',
    joovisUsage: '빌드 후 dist 폴더의 정적 파일은 배포 가능한 artifact입니다.',
    checkQuestion: '이번 작업의 최종 산출물은 어떤 파일인가요?',
    codexPromptExample: '빌드 artifact가 정적 파일만 포함하는지 확인해 주세요.',
    category: 'Data / Schema',
  },
  {
    id: 'provenance',
    term: 'Provenance',
    pronunciation: '프로버넌스',
    koreanMeaning: '정보나 변경이 어디에서 왔는지에 대한 출처 기록',
    simpleMeaning: '데이터와 변경의 출신을 추적하는 개념입니다.',
    joovisUsage: '용어 설명은 이 독립 학습 앱을 위해 작성되었다는 provenance를 가집니다.',
    checkQuestion: '이 정보가 어디서 왔는지 설명할 수 있나요?',
    codexPromptExample: '새 용어를 추가할 때 provenance가 모호한 추측 설명은 피하세요.',
    category: 'Data / Schema',
  },
  {
    id: 'diff',
    term: 'Diff',
    pronunciation: '디프',
    koreanMeaning: '이전 상태와 현재 상태의 차이',
    simpleMeaning: '무엇이 바뀌었는지 보여 주는 변경 목록입니다.',
    joovisUsage: '리뷰에서는 이 PWA 파일 diff만 확인합니다.',
    checkQuestion: '이 변경에서 실제로 달라진 줄은 어디인가요?',
    codexPromptExample: '현재 workspace 안의 diff만 요약하고 범위 밖 파일은 언급하지 마세요.',
    category: 'Git / Change Control',
  },
  {
    id: 'runtime',
    term: 'Runtime',
    pronunciation: '런타임',
    koreanMeaning: '앱이 실제로 실행되는 시간과 환경',
    simpleMeaning: '사용자가 앱을 열어 사용하는 순간의 상태입니다.',
    joovisUsage: '이 PWA runtime은 브라우저이며 상태는 localStorage에만 남습니다.',
    checkQuestion: '이 동작은 빌드 시점인가요, 실행 시점인가요?',
    codexPromptExample: 'Runtime 동작은 브라우저와 localStorage로만 처리하고 서버는 만들지 마세요.',
    category: 'Runtime / Integration',
  },
  {
    id: 'static',
    term: 'Static',
    pronunciation: '스태틱',
    koreanMeaning: '서버 계산 없이 미리 만들어진 파일로 제공되는 방식',
    simpleMeaning: 'HTML, CSS, JS 파일만으로 실행되는 구조입니다.',
    joovisUsage: 'JOOVIS Terms Cockpit은 static-only 앱입니다.',
    checkQuestion: '이 기능이 정적 파일만으로 가능한가요?',
    codexPromptExample: 'Static PWA로 유지하고 데이터는 번들된 TypeScript 파일에 넣어 주세요.',
    category: 'Architecture',
  },
  {
    id: 'guard',
    term: 'Guard',
    pronunciation: '가드',
    koreanMeaning: '잘못된 입력이나 위험한 흐름을 막는 보호 조건',
    simpleMeaning: '문제가 생기기 전에 막는 조건문이나 규칙입니다.',
    joovisUsage: 'workspace path 확인은 잘못된 폴더 작업을 막는 guard입니다.',
    checkQuestion: '위험한 작업 전에 어떤 조건을 확인해야 하나요?',
    codexPromptExample: '파일을 수정하기 전에 workspace guard를 확인하고 결과를 보고해 주세요.',
    category: 'Boundary / Safety',
  },
  {
    id: 'checker',
    term: 'Checker',
    pronunciation: '체커',
    koreanMeaning: '규칙 위반이나 오류를 찾아내는 검사 도구나 로직',
    simpleMeaning: '틀린 부분을 찾아 주는 검사기입니다.',
    joovisUsage: 'TypeScript 빌드는 용어 데이터와 컴포넌트 contract를 확인하는 checker입니다.',
    checkQuestion: '이 변경을 어떤 검사로 확인할 수 있나요?',
    codexPromptExample: '구현 후 checker 역할로 npm run build를 실행해 주세요.',
    category: 'Review / QA',
  },
  {
    id: 'smoke-test',
    term: 'Smoke Test',
    pronunciation: '스모크 테스트',
    koreanMeaning: '핵심 기능이 크게 깨지지 않았는지 빠르게 보는 검사',
    simpleMeaning: '앱이 기본적으로 켜지고 주요 버튼이 보이는지 확인합니다.',
    joovisUsage: '빌드 성공과 홈 화면 렌더링은 이 앱의 smoke test입니다.',
    checkQuestion: '가장 먼저 확인해야 할 기본 동작은 무엇인가요?',
    codexPromptExample: '검색, 랜덤 용어, 즐겨찾기 버튼이 보이는지 smoke test 관점으로 확인해 주세요.',
    category: 'Review / QA',
  },
  {
    id: 'regression',
    term: 'Regression',
    pronunciation: '리그레션',
    koreanMeaning: '예전에 되던 기능이 변경 후 깨지는 문제',
    simpleMeaning: '고치다가 멀쩡하던 것을 망가뜨린 상황입니다.',
    joovisUsage: '검색을 수정했는데 즐겨찾기 저장이 깨지면 regression입니다.',
    checkQuestion: '이번 변경으로 기존 기능 중 무엇이 깨질 수 있나요?',
    codexPromptExample: '새 필터를 추가하면서 기존 search와 review status에 regression이 없는지 봐 주세요.',
    category: 'Review / QA',
  },
  {
    id: 'acceptance-criteria',
    term: 'Acceptance Criteria',
    pronunciation: '억셉턴스 크라이테리아',
    koreanMeaning: '작업 완료를 판단하는 구체적인 조건',
    simpleMeaning: '끝났다고 말할 수 있는 체크리스트입니다.',
    joovisUsage: '80개 이상 용어, PWA manifest, service worker, 빌드 성공이 acceptance criteria입니다.',
    checkQuestion: '무엇을 만족해야 PASS라고 할 수 있나요?',
    codexPromptExample: '요구사항을 acceptance criteria로 바꾸고 완료 여부를 하나씩 검증해 주세요.',
    category: 'Review / QA',
  },
  {
    id: 'handoff',
    term: 'Handoff',
    pronunciation: '핸드오프',
    koreanMeaning: '다음 사람이 이어서 할 수 있도록 전달하는 정리',
    simpleMeaning: '작업 상태와 남은 일을 넘겨주는 것입니다.',
    joovisUsage: '최종 보고서는 바뀐 파일과 검증 결과를 handoff합니다.',
    checkQuestion: '다음 사람이 이어서 보려면 어떤 정보가 필요할까요?',
    codexPromptExample: '완료 후 commands run, validation, risks를 포함해 handoff 형식으로 보고해 주세요.',
    category: 'Git / Change Control',
  },
  {
    id: 'telemetry',
    term: 'Telemetry',
    pronunciation: '텔레메트리',
    koreanMeaning: '시스템 상태나 사용 현황을 관찰하기 위한 측정 정보',
    simpleMeaning: '앱이 어떻게 쓰이는지 보는 신호입니다.',
    joovisUsage: '이 앱은 외부 telemetry를 보내지 않고 로컬 카운트만 보여 줍니다.',
    checkQuestion: '측정 정보가 외부로 나가도 되는 조건인가요?',
    codexPromptExample: 'Telemetry는 추가하지 말고 localStorage 기반 카운트만 표시해 주세요.',
    category: 'Runtime / Integration',
  },
  {
    id: 'upstream',
    term: 'Upstream',
    pronunciation: '업스트림',
    koreanMeaning: '현재 작업보다 앞단에서 입력이나 기준을 제공하는 쪽',
    simpleMeaning: '내 코드가 받는 원천입니다.',
    joovisUsage: 'devTerms 데이터는 카드 UI의 upstream 입력입니다.',
    checkQuestion: '이 화면은 어떤 데이터나 결정에 의존하나요?',
    codexPromptExample: 'UI를 고치기 전에 upstream 데이터 구조를 먼저 확인해 주세요.',
    category: 'Architecture',
  },
  {
    id: 'downstream',
    term: 'Downstream',
    pronunciation: '다운스트림',
    koreanMeaning: '현재 작업의 결과를 받아 쓰는 뒤쪽 흐름',
    simpleMeaning: '내 변경의 영향을 받는 곳입니다.',
    joovisUsage: 'DevTerm 필드명을 바꾸면 downstream 카드 렌더링과 검색이 영향을 받습니다.',
    checkQuestion: '이 변경을 받아 쓰는 화면이나 함수는 어디인가요?',
    codexPromptExample: '필드명을 바꾸면 downstream 컴포넌트까지 함께 업데이트해 주세요.',
    category: 'Architecture',
  },
  {
    id: 'dependency',
    term: 'Dependency',
    pronunciation: '디펜던시',
    koreanMeaning: '코드나 기능이 동작하기 위해 의존하는 대상',
    simpleMeaning: '없으면 작동하지 않는 필요 요소입니다.',
    joovisUsage: '이 프로젝트의 앱 의존성은 React와 React DOM뿐입니다.',
    checkQuestion: '이 기능을 위해 새 의존성이 꼭 필요한가요?',
    codexPromptExample: '새 dependency를 추가하지 말고 React 기본 기능으로 구현해 주세요.',
    category: 'Architecture',
  },
  {
    id: 'coupling',
    term: 'Coupling',
    pronunciation: '커플링',
    koreanMeaning: '두 부분이 서로 강하게 묶여 있는 정도',
    simpleMeaning: '한쪽을 바꾸면 다른 쪽도 쉽게 흔들리는 상태입니다.',
    joovisUsage: '검색 로직이 카드 UI에 과하게 섞이면 coupling이 커집니다.',
    checkQuestion: '이 코드는 다른 부분을 너무 많이 알고 있지 않나요?',
    codexPromptExample: '상태 저장 로직과 화면 렌더링의 coupling을 낮게 유지해 주세요.',
    category: 'Architecture',
  },
  {
    id: 'decoupling',
    term: 'Decoupling',
    pronunciation: '디커플링',
    koreanMeaning: '서로 묶인 부분을 느슨하게 분리하는 설계',
    simpleMeaning: '한쪽 변경이 다른 쪽에 덜 퍼지게 만드는 것입니다.',
    joovisUsage: 'storage.ts를 분리하면 localStorage 접근과 화면 로직이 decoupling됩니다.',
    checkQuestion: '어떤 책임을 분리하면 변경이 쉬워질까요?',
    codexPromptExample: 'localStorage 코드는 storage.ts로 decoupling해서 App.tsx를 단순하게 유지해 주세요.',
    category: 'Architecture',
  },
  {
    id: 'adapter',
    term: 'Adapter',
    pronunciation: '어댑터',
    koreanMeaning: '서로 다른 형태를 맞춰 주는 변환 계층',
    simpleMeaning: '한쪽 형식을 다른 쪽이 이해하는 형식으로 바꿉니다.',
    joovisUsage: 'storage.ts는 localStorage 문자열과 앱 상태 사이의 adapter 역할을 합니다.',
    checkQuestion: '형식 차이를 어디에서 흡수하나요?',
    codexPromptExample: '브라우저 저장소 접근은 adapter 함수로 감싸서 컴포넌트가 직접 파싱하지 않게 해 주세요.',
    category: 'Architecture',
  },
  {
    id: 'port',
    term: 'Port',
    pronunciation: '포트',
    koreanMeaning: '핵심 로직이 외부와 만나는 추상 접점',
    simpleMeaning: '바깥과 연결되는 교체 가능한 입구입니다.',
    joovisUsage: '저장소 helper 함수는 앱이 localStorage에 접근하는 port처럼 볼 수 있습니다.',
    checkQuestion: '외부 세부 구현을 바꿔도 핵심 로직이 유지되나요?',
    codexPromptExample: '저장 port를 작게 두고 외부 서비스 연결은 만들지 마세요.',
    category: 'Architecture',
  },
  {
    id: 'pipeline',
    term: 'Pipeline',
    pronunciation: '파이프라인',
    koreanMeaning: '여러 처리를 순서대로 통과하는 흐름',
    simpleMeaning: '입력에서 결과까지 이어지는 단계 묶음입니다.',
    joovisUsage: '검색어 정규화, 카테고리 필터, 즐겨찾기 필터가 카드 목록 pipeline입니다.',
    checkQuestion: '이 데이터는 어떤 순서로 처리되나요?',
    codexPromptExample: '목록 pipeline을 query, category, favorites 순서로 읽기 쉽게 정리해 주세요.',
    category: 'Runtime / Integration',
  },
  {
    id: 'orchestration',
    term: 'Orchestration',
    pronunciation: '오케스트레이션',
    koreanMeaning: '여러 작업을 적절한 순서로 조율하는 것',
    simpleMeaning: '각 기능이 언제 어떻게 실행될지 묶어 관리합니다.',
    joovisUsage: 'App.tsx는 검색, 필터, 저장 상태를 조율하는 orchestration 지점입니다.',
    checkQuestion: '여러 상태 변경이 어디에서 조율되나요?',
    codexPromptExample: '상태 orchestration은 App.tsx 안에 두고 외부 런타임 시스템은 추가하지 마세요.',
    category: 'Runtime / Integration',
  },
  {
    id: 'fixture',
    term: 'Fixture',
    pronunciation: '픽스처',
    koreanMeaning: '테스트나 검증에 쓰는 고정 입력 데이터',
    simpleMeaning: '항상 같은 결과를 기대할 수 있는 샘플 데이터입니다.',
    joovisUsage: 'devTerms 일부 항목은 검색 동작을 확인하는 fixture처럼 사용할 수 있습니다.',
    checkQuestion: '검증에 사용할 안정적인 샘플은 무엇인가요?',
    codexPromptExample: '검색 검증용 fixture로 Schema와 Fail-closed 항목을 확인해 주세요.',
    category: 'Review / QA',
  },
  {
    id: 'mock',
    term: 'Mock',
    pronunciation: '목',
    koreanMeaning: '실제 대상을 흉내 내는 테스트용 대체물',
    simpleMeaning: '진짜 대신 쓰는 가짜 객체입니다.',
    joovisUsage: '이 앱은 외부 연동이 없으므로 네트워크 mock이 필요 없습니다.',
    checkQuestion: '실제 대상 없이 테스트하려면 무엇을 흉내 내야 하나요?',
    codexPromptExample: '외부 mock을 만들지 말고 정적 데이터로만 UI를 검증해 주세요.',
    category: 'Review / QA',
  },
  {
    id: 'stub',
    term: 'Stub',
    pronunciation: '스텁',
    koreanMeaning: '간단한 고정 응답만 돌려주는 대체 코드',
    simpleMeaning: '복잡한 동작 없이 자리만 채우는 간단한 함수입니다.',
    joovisUsage: '초기 UI 확인에는 고정 용어 배열이 stub 데이터처럼 쓰일 수 있습니다.',
    checkQuestion: '임시 구현이 실제 요구를 가리고 있지는 않나요?',
    codexPromptExample: 'Stub으로 끝내지 말고 실제 80개 이상 용어 데이터를 채워 주세요.',
    category: 'Review / QA',
  },
  {
    id: 'sandbox',
    term: 'Sandbox',
    pronunciation: '샌드박스',
    koreanMeaning: '영향 범위를 제한한 안전한 실행 공간',
    simpleMeaning: '실수해도 밖으로 번지지 않게 만든 공간입니다.',
    joovisUsage: '현재 workspace 폴더가 이 독립 앱을 만드는 sandbox입니다.',
    checkQuestion: '작업이 sandbox 밖으로 나가지 않도록 무엇을 확인하나요?',
    codexPromptExample: 'Sandbox를 C:\\dev\\joovis-terms-cockpit으로 제한하고 다른 프로젝트를 보지 마세요.',
    category: 'Boundary / Safety',
  },
  {
    id: 'dry-run',
    term: 'Dry Run',
    pronunciation: '드라이 런',
    koreanMeaning: '실제 변경 없이 결과를 미리 확인하는 실행',
    simpleMeaning: '실행하면 어떻게 될지 먼저 보는 연습입니다.',
    joovisUsage: '삭제나 대량 변경 전에는 대상 파일을 먼저 확인하는 dry run 사고방식이 필요합니다.',
    checkQuestion: '실제 변경 전에 확인할 수 있는 방법이 있나요?',
    codexPromptExample: '파일을 지우기 전에 대상 목록을 먼저 확인하는 dry run 단계를 거쳐 주세요.',
    category: 'Git / Change Control',
  },
  {
    id: 'idempotent',
    term: 'Idempotent',
    pronunciation: '아이뎀포턴트',
    koreanMeaning: '여러 번 실행해도 결과가 더 변하지 않는 성질',
    simpleMeaning: '같은 일을 반복해도 같은 상태로 남는 것입니다.',
    joovisUsage: '같은 용어를 여러 번 즐겨찾기해도 Set 구조라 결과가 하나로 유지됩니다.',
    checkQuestion: '이 동작을 반복 실행하면 상태가 중복되나요?',
    codexPromptExample: '즐겨찾기 저장은 idempotent하게 만들어 중복 id가 생기지 않게 해 주세요.',
    category: 'Runtime / Integration',
  },
  {
    id: 'side-effect',
    term: 'Side Effect',
    pronunciation: '사이드 이펙트',
    koreanMeaning: '함수 밖의 상태를 바꾸는 부수 효과',
    simpleMeaning: '계산 결과 외에 저장소나 화면 상태를 바꾸는 일입니다.',
    joovisUsage: 'localStorage 저장은 이 앱에서 의도된 side effect입니다.',
    checkQuestion: '이 함수가 외부 상태를 바꾸나요?',
    codexPromptExample: 'Side effect는 localStorage 저장으로만 제한하고 외부 호출은 추가하지 마세요.',
    category: 'Boundary / Safety',
  },
  {
    id: 'invariant',
    term: 'Invariant',
    pronunciation: '인베리언트',
    koreanMeaning: '어떤 변경 후에도 항상 유지되어야 하는 조건',
    simpleMeaning: '절대 깨지면 안 되는 약속입니다.',
    joovisUsage: '모든 용어는 DevTerm 필드를 빠짐없이 가진다는 조건이 invariant입니다.',
    checkQuestion: '항상 참이어야 하는 조건은 무엇인가요?',
    codexPromptExample: '80개 이상 용어와 DevTerm field invariant를 깨지 않는지 확인해 주세요.',
    category: 'Boundary / Safety',
  },
  {
    id: 'fail-closed',
    term: 'Fail-closed',
    pronunciation: '페일 클로즈드',
    koreanMeaning: '실패하면 허용하지 않고 안전한 쪽으로 닫히는 방식',
    simpleMeaning: '불확실하면 멈추는 안전 원칙입니다.',
    joovisUsage: 'workspace가 맞지 않으면 작업을 멈추는 것이 fail-closed입니다.',
    checkQuestion: '불확실할 때 계속 진행하나요, 안전하게 멈추나요?',
    codexPromptExample: '경로 확인이 실패하면 fail-closed로 멈추고 BLOCKED를 보고해 주세요.',
    category: 'Boundary / Safety',
  },
  {
    id: 'rollback',
    term: 'Rollback',
    pronunciation: '롤백',
    koreanMeaning: '변경을 이전의 안전한 상태로 되돌리는 것',
    simpleMeaning: '문제가 생기면 전 상태로 복구합니다.',
    joovisUsage: 'PWA 변경이 빌드를 깨면 해당 변경만 되돌릴 수 있어야 합니다.',
    checkQuestion: '문제가 생겼을 때 어떤 변경을 되돌리면 되나요?',
    codexPromptExample: '불필요한 파일 변경을 섞지 말고 rollback이 쉬운 작은 변경으로 유지해 주세요.',
    category: 'Git / Change Control',
  },
  {
    id: 'migration',
    term: 'Migration',
    pronunciation: '마이그레이션',
    koreanMeaning: '데이터나 구조를 새 형태로 옮기는 작업',
    simpleMeaning: '기존 상태를 새 규칙에 맞게 바꾸는 과정입니다.',
    joovisUsage: 'localStorage 키 구조를 바꾸면 기존 사용자 상태 migration을 고려해야 합니다.',
    checkQuestion: '이 변경이 기존 저장 데이터를 어떻게 다루나요?',
    codexPromptExample: '저장 schema를 바꿀 때 migration 없이 기존 즐겨찾기를 잃지 않게 해 주세요.',
    category: 'Data / Schema',
  },
  {
    id: 'prompt',
    term: 'Prompt',
    pronunciation: '프롬프트',
    koreanMeaning: 'AI에게 원하는 작업을 설명하는 입력 문장',
    simpleMeaning: 'Codex에게 일을 부탁하는 문장입니다.',
    joovisUsage: '좋은 prompt는 목표, 범위, 금지사항, 검증 방법을 함께 말합니다.',
    checkQuestion: '요청 문장에 목표와 제한이 충분히 들어 있나요?',
    codexPromptExample: 'Prompt에 작업 폴더와 금지 범위를 명시하고 구현 후 build를 실행해 주세요.',
    category: 'AI Command',
  },
  {
    id: 'instruction',
    term: 'Instruction',
    pronunciation: '인스트럭션',
    koreanMeaning: '반드시 따라야 하는 지시나 규칙',
    simpleMeaning: 'AI나 사람이 지켜야 하는 명령입니다.',
    joovisUsage: '외부 연동 금지 instruction은 구현 선택을 제한합니다.',
    checkQuestion: '이 작업에서 가장 우선순위가 높은 지시는 무엇인가요?',
    codexPromptExample: 'Instruction을 우선순위대로 읽고 충돌이 있으면 더 안전한 쪽을 선택해 주세요.',
    category: 'AI Command',
  },
  {
    id: 'system-instruction',
    term: 'System Instruction',
    pronunciation: '시스템 인스트럭션',
    koreanMeaning: '대화나 도구 사용의 최상위 동작 규칙',
    simpleMeaning: 'AI가 항상 지켜야 하는 운영 규칙입니다.',
    joovisUsage: '파일 수정 방식이나 보고 형식은 system instruction의 영향을 받습니다.',
    checkQuestion: '사용자 요청보다 먼저 지켜야 하는 상위 규칙이 있나요?',
    codexPromptExample: 'System instruction과 사용자 요구를 모두 만족하는 최소 구현을 해 주세요.',
    category: 'AI Command',
  },
  {
    id: 'user-intent',
    term: 'User Intent',
    pronunciation: '유저 인텐트',
    koreanMeaning: '사용자가 실제로 달성하려는 목적',
    simpleMeaning: '문장 뒤에 있는 진짜 목표입니다.',
    joovisUsage: '이 앱의 user intent는 용어를 빠르게 배우고 복습하는 것입니다.',
    checkQuestion: '사용자가 원하는 최종 결과는 무엇인가요?',
    codexPromptExample: 'User intent를 학습용 모바일 PWA로 보고 기능을 단순하게 유지해 주세요.',
    category: 'AI Command',
  },
  {
    id: 'constraint',
    term: 'Constraint',
    pronunciation: '컨스트레인트',
    koreanMeaning: '선택지를 제한하는 조건',
    simpleMeaning: '반드시 지켜야 하는 제약입니다.',
    joovisUsage: '백엔드, DB, 로그인 금지는 이 앱의 핵심 constraint입니다.',
    checkQuestion: '이 설계에서 절대 하지 말아야 할 일은 무엇인가요?',
    codexPromptExample: 'Constraint를 지켜서 외부 서비스 없이 localStorage만 사용해 주세요.',
    category: 'Boundary / Safety',
  },
  {
    id: 'assumption',
    term: 'Assumption',
    pronunciation: '어섬션',
    koreanMeaning: '명시되지 않았지만 임시로 참이라고 두는 전제',
    simpleMeaning: '확실하지 않지만 진행을 위해 둔 가정입니다.',
    joovisUsage: '명시가 없으면 mobile-first 레이아웃을 기본 assumption으로 둡니다.',
    checkQuestion: '지금 내가 가정하고 있는 것은 무엇인가요?',
    codexPromptExample: '불명확한 부분은 안전한 assumption으로 처리하고 최종 보고에 남겨 주세요.',
    category: 'AI Command',
  },
  {
    id: 'clarifying-question',
    term: 'Clarifying Question',
    pronunciation: '클래리파잉 퀘스천',
    koreanMeaning: '모호한 요구를 분명히 하기 위해 묻는 질문',
    simpleMeaning: '잘못 구현하기 전에 확인하는 질문입니다.',
    joovisUsage: '경로가 불분명하면 구현 전에 clarifying question이 필요합니다.',
    checkQuestion: '지금 묻지 않으면 위험한 모호함이 있나요?',
    codexPromptExample: '위험한 선택지가 있으면 한 가지 clarifying question만 묻고 기다려 주세요.',
    category: 'AI Command',
  },
  {
    id: 'plan',
    term: 'Plan',
    pronunciation: '플랜',
    koreanMeaning: '작업을 어떤 순서로 할지 정한 실행 흐름',
    simpleMeaning: '무엇을 먼저 하고 다음에 할지 정리한 것입니다.',
    joovisUsage: 'scaffold, data, UI, PWA, build 순서가 간단한 plan입니다.',
    checkQuestion: '검증까지 포함한 순서가 있나요?',
    codexPromptExample: '작업 plan을 세운 뒤 각 단계가 끝날 때 상태를 업데이트해 주세요.',
    category: 'AI Command',
  },
  {
    id: 'checklist',
    term: 'Checklist',
    pronunciation: '체크리스트',
    koreanMeaning: '빠뜨리지 않기 위해 확인할 항목 목록',
    simpleMeaning: '끝내기 전에 보는 확인표입니다.',
    joovisUsage: '최종 보고의 boundary confirmation은 안전 checklist입니다.',
    checkQuestion: '완료 전에 반드시 확인할 항목은 무엇인가요?',
    codexPromptExample: '요구사항을 checklist로 보고 누락된 기능이 있으면 채워 주세요.',
    category: 'Review / QA',
  },
  {
    id: 'checkpoint',
    term: 'Checkpoint',
    pronunciation: '체크포인트',
    koreanMeaning: '긴 작업 중 중간 상태를 확인하는 지점',
    simpleMeaning: '여기까지 맞는지 확인하는 멈춤점입니다.',
    joovisUsage: 'npm install 성공, 빌드 성공, PWA 파일 존재가 checkpoint입니다.',
    checkQuestion: '다음 단계로 가기 전에 무엇을 확인해야 하나요?',
    codexPromptExample: '파일 편집 후 build를 checkpoint로 삼아 오류를 바로 수정해 주세요.',
    category: 'Review / QA',
  },
  {
    id: 'token-budget',
    term: 'Token Budget',
    pronunciation: '토큰 버짓',
    koreanMeaning: 'AI가 한 번에 읽고 쓸 수 있는 문맥의 사용량 한도',
    simpleMeaning: '대화와 코드 설명에 쓸 수 있는 공간입니다.',
    joovisUsage: '필요한 파일만 읽는 것이 token budget 관리입니다.',
    checkQuestion: '지금 필요한 정보만 읽고 있나요?',
    codexPromptExample: 'Token budget을 아끼기 위해 관련 파일만 읽고 요약해 주세요.',
    category: 'AI Command',
  },
  {
    id: 'state',
    term: 'State',
    pronunciation: '스테이트',
    koreanMeaning: '현재 화면이나 기능이 기억하고 있는 값',
    simpleMeaning: '앱의 현재 상태입니다.',
    joovisUsage: '검색어, 선택 카테고리, 즐겨찾기, 복습 상태가 React state입니다.',
    checkQuestion: '이 값은 화면 상태인가요, 저장해야 하는 사용자 상태인가요?',
    codexPromptExample: 'State를 검색 필터와 저장 데이터로 나누어 관리해 주세요.',
    category: 'Runtime / Integration',
  },
  {
    id: 'reducer',
    term: 'Reducer',
    pronunciation: '리듀서',
    koreanMeaning: '현재 상태와 action으로 다음 상태를 만드는 함수',
    simpleMeaning: '상태 변경 규칙을 한곳에 모으는 방식입니다.',
    joovisUsage: '이 앱은 작아서 reducer 없이 useState로 충분합니다.',
    checkQuestion: '상태 변경이 복잡해서 규칙을 모을 필요가 있나요?',
    codexPromptExample: 'Reducer가 필요할 만큼 복잡하지 않으면 단순한 useState로 유지해 주세요.',
    category: 'Runtime / Integration',
  },
  {
    id: 'selector',
    term: 'Selector',
    pronunciation: '셀렉터',
    koreanMeaning: '큰 상태나 데이터에서 필요한 값만 골라내는 함수',
    simpleMeaning: '보여 줄 데이터만 추려내는 필터입니다.',
    joovisUsage: 'visibleTerms 계산은 검색과 카테고리를 적용하는 selector입니다.',
    checkQuestion: '화면에 필요한 값은 어디서 계산하나요?',
    codexPromptExample: 'Term list selector를 useMemo로 만들고 검색 필드를 모두 포함해 주세요.',
    category: 'Runtime / Integration',
  },
  {
    id: 'validation',
    term: 'Validation',
    pronunciation: '밸리데이션',
    koreanMeaning: '값이 정해진 규칙에 맞는지 확인하는 것',
    simpleMeaning: '입력이나 데이터가 올바른지 검사합니다.',
    joovisUsage: 'TypeScript 타입과 빌드는 용어 데이터 validation 역할을 합니다.',
    checkQuestion: '이 데이터가 올바른지 어떤 규칙으로 확인하나요?',
    codexPromptExample: 'Validation 오류가 생기면 데이터 shape를 고쳐 build가 통과하게 해 주세요.',
    category: 'Data / Schema',
  },
  {
    id: 'normalization',
    term: 'Normalization',
    pronunciation: '노멀라이제이션',
    koreanMeaning: '비교와 저장이 쉽도록 값을 일정한 형태로 바꾸는 것',
    simpleMeaning: '검색하기 좋게 소문자나 공백 처리 등을 맞춥니다.',
    joovisUsage: '검색어를 소문자로 바꾸는 과정이 normalization입니다.',
    checkQuestion: '비교 전에 같은 기준으로 값을 맞췄나요?',
    codexPromptExample: 'Search normalization을 적용해서 영어와 한국어 검색이 안정적으로 되게 해 주세요.',
    category: 'Data / Schema',
  },
  {
    id: 'serialization',
    term: 'Serialization',
    pronunciation: '시리얼라이제이션',
    koreanMeaning: '객체를 저장 가능한 문자열 형태로 바꾸는 것',
    simpleMeaning: '저장소에 넣기 위해 JSON 문자열로 바꾸는 과정입니다.',
    joovisUsage: '즐겨찾기 Set을 배열로 바꾼 뒤 JSON으로 저장하는 것이 serialization입니다.',
    checkQuestion: '이 값은 저장 가능한 형태로 변환되나요?',
    codexPromptExample: 'localStorage 저장 전에 Set을 serialization 가능한 배열로 바꿔 주세요.',
    category: 'Data / Schema',
  },
  {
    id: 'versioning',
    term: 'Versioning',
    pronunciation: '버저닝',
    koreanMeaning: '변경 이력을 구분하기 위해 버전을 붙이는 것',
    simpleMeaning: '어떤 버전의 구조인지 표시합니다.',
    joovisUsage: 'service worker cache 이름에 versioning을 쓰면 새 빌드 반영이 쉬워집니다.',
    checkQuestion: '이 저장 구조나 캐시는 버전 구분이 필요한가요?',
    codexPromptExample: 'Service worker cache 이름에 versioning을 넣어 오래된 캐시를 정리해 주세요.',
    category: 'Git / Change Control',
  },
  {
    id: 'backward-compatibility',
    term: 'Backward Compatibility',
    pronunciation: '백워드 컴패터빌리티',
    koreanMeaning: '새 코드가 기존 데이터나 사용 방식과 계속 맞는 성질',
    simpleMeaning: '예전 상태를 새 버전에서도 읽을 수 있는 것입니다.',
    joovisUsage: 'localStorage 키를 바꿀 때 기존 즐겨찾기를 잃지 않는 것이 backward compatibility입니다.',
    checkQuestion: '기존 사용자의 저장 상태가 계속 읽히나요?',
    codexPromptExample: '기존 localStorage 값을 고려해 backward compatibility를 유지해 주세요.',
    category: 'Data / Schema',
  },
  {
    id: 'forward-compatibility',
    term: 'Forward Compatibility',
    pronunciation: '포워드 컴패터빌리티',
    koreanMeaning: '미래 구조 일부를 만나도 크게 깨지지 않는 성질',
    simpleMeaning: '새로운 값이 와도 안전하게 무시하거나 처리합니다.',
    joovisUsage: '알 수 없는 review status가 있어도 앱이 기본 상태로 보이면 forward compatibility가 좋습니다.',
    checkQuestion: '알 수 없는 값이 와도 화면이 안전하게 동작하나요?',
    codexPromptExample: 'Forward compatibility를 위해 모르는 상태값은 new처럼 표시해 주세요.',
    category: 'Data / Schema',
  },
  {
    id: 'fallback',
    term: 'Fallback',
    pronunciation: '폴백',
    koreanMeaning: '기본 방법이 실패했을 때 쓰는 대체 방법',
    simpleMeaning: '안 될 때 대신 쓰는 안전한 선택지입니다.',
    joovisUsage: 'localStorage 읽기에 실패하면 빈 즐겨찾기 목록으로 fallback합니다.',
    checkQuestion: '실패했을 때 사용자에게 안전한 기본값이 있나요?',
    codexPromptExample: 'Storage 접근이 실패하면 fallback으로 빈 상태를 사용하게 해 주세요.',
    category: 'Boundary / Safety',
  },
  {
    id: 'timeout',
    term: 'Timeout',
    pronunciation: '타임아웃',
    koreanMeaning: '정해진 시간 안에 끝나지 않으면 중단하는 제한',
    simpleMeaning: '너무 오래 걸리면 멈추는 시간 제한입니다.',
    joovisUsage: '이 앱에는 외부 요청이 없어서 runtime timeout 처리가 거의 필요 없습니다.',
    checkQuestion: '끝나지 않을 수 있는 작업이 있나요?',
    codexPromptExample: '외부 요청을 만들지 말고 timeout이 필요한 흐름 자체를 추가하지 마세요.',
    category: 'Runtime / Integration',
  },
  {
    id: 'retry',
    term: 'Retry',
    pronunciation: '리트라이',
    koreanMeaning: '실패한 작업을 다시 시도하는 것',
    simpleMeaning: '한 번 더 해 보는 복구 방식입니다.',
    joovisUsage: 'service worker 등록 실패는 앱 사용을 막지 않으므로 복잡한 retry UI를 만들지 않습니다.',
    checkQuestion: '다시 시도하면 실제로 성공 가능성이 높아지나요?',
    codexPromptExample: 'Retry 로직을 복잡하게 만들지 말고 정적 앱으로 단순하게 유지해 주세요.',
    category: 'Runtime / Integration',
  },
  {
    id: 'cache',
    term: 'Cache',
    pronunciation: '캐시',
    koreanMeaning: '다시 쓰기 위해 임시로 저장해 둔 데이터나 파일',
    simpleMeaning: '빠르고 오프라인에 쓰기 위해 보관하는 복사본입니다.',
    joovisUsage: 'service worker cache는 앱 shell 파일을 저장해 홈 화면 실행을 돕습니다.',
    checkQuestion: '오래된 cache가 새 변경을 가리지 않나요?',
    codexPromptExample: 'Cache 이름을 버전으로 관리하고 오래된 cache를 activate 단계에서 지워 주세요.',
    category: 'Runtime / Integration',
  },
  {
    id: 'offline-first',
    term: 'Offline-first',
    pronunciation: '오프라인 퍼스트',
    koreanMeaning: '네트워크가 없어도 먼저 동작하도록 설계하는 방식',
    simpleMeaning: '인터넷 없이도 기본 기능이 되는 앱입니다.',
    joovisUsage: '이 학습 PWA는 정적 데이터와 localStorage로 offline-first에 가깝게 동작합니다.',
    checkQuestion: '네트워크 없이도 핵심 학습 기능이 되나요?',
    codexPromptExample: 'Offline-first를 위해 모든 용어 데이터를 번들 안에 포함해 주세요.',
    category: 'Runtime / Integration',
  },
  {
    id: 'least-privilege',
    term: 'Least Privilege',
    pronunciation: '리스트 프리빌리지',
    koreanMeaning: '필요한 최소 권한만 사용하는 원칙',
    simpleMeaning: '할 일에 꼭 필요한 접근만 허용합니다.',
    joovisUsage: '이 앱은 계정 권한 없이 브라우저 저장소만 씁니다.',
    checkQuestion: '이 기능에 이 권한이 정말 필요한가요?',
    codexPromptExample: 'Least privilege 원칙으로 localStorage 외 권한을 요구하지 않게 해 주세요.',
    category: 'Boundary / Safety',
  },
  {
    id: 'redaction',
    term: 'Redaction',
    pronunciation: '리댁션',
    koreanMeaning: '민감한 정보를 가리거나 제거하는 것',
    simpleMeaning: '보이면 안 되는 값을 숨기는 처리입니다.',
    joovisUsage: '이 앱은 비밀값을 쓰지 않지만 보고 전 민감 정보가 없는지 redaction 관점으로 봅니다.',
    checkQuestion: '공개하면 안 되는 정보가 출력에 포함되어 있나요?',
    codexPromptExample: '보고 전 redaction이 필요한 값이 있는지 확인하고 비밀값은 만들지 마세요.',
    category: 'Boundary / Safety',
  },
  {
    id: 'secret',
    term: 'Secret',
    pronunciation: '시크릿',
    koreanMeaning: '노출되면 안 되는 인증 정보나 민감한 값',
    simpleMeaning: '코드에 넣으면 안 되는 비밀 정보입니다.',
    joovisUsage: 'JOOVIS Terms Cockpit은 secret이나 .env 없이 동작해야 합니다.',
    checkQuestion: '이 값이 코드나 브라우저에 저장되어도 안전한가요?',
    codexPromptExample: 'Secret, .env, 토큰을 만들지 말고 정적 데이터만 사용해 주세요.',
    category: 'Boundary / Safety',
  },
  {
    id: 'audit-trail',
    term: 'Audit Trail',
    pronunciation: '오딧 트레일',
    koreanMeaning: '누가 무엇을 언제 바꿨는지 따라갈 수 있는 기록',
    simpleMeaning: '변경의 흔적을 추적할 수 있게 남긴 것입니다.',
    joovisUsage: 'git diff와 최종 보고는 이번 작업의 audit trail로 볼 수 있습니다.',
    checkQuestion: '이 변경을 나중에 추적할 수 있나요?',
    codexPromptExample: 'Audit trail이 흐려지지 않게 관련 없는 파일 변경은 만들지 마세요.',
    category: 'Git / Change Control',
  },
  {
    id: 'read-only-mode',
    term: 'Read-only Mode',
    pronunciation: '리드 온리 모드',
    koreanMeaning: '읽기만 허용하고 쓰기는 막는 상태',
    simpleMeaning: '확인만 하고 변경하지 않는 방식입니다.',
    joovisUsage: '기존 프로젝트 접근 금지는 read-only보다 더 강한 boundary입니다.',
    checkQuestion: '지금은 읽어도 되는가요, 아예 접근하면 안 되나요?',
    codexPromptExample: '다른 JOOVIS 저장소는 read-only로도 접근하지 말고 현재 폴더만 사용해 주세요.',
    category: 'Boundary / Safety',
  },
  {
    id: 'no-op',
    term: 'No-op',
    pronunciation: '노옵',
    koreanMeaning: '아무 변화도 만들지 않는 동작',
    simpleMeaning: '실행해도 상태가 바뀌지 않는 일입니다.',
    joovisUsage: '저장 실패는 앱이 멈추지 않도록 no-op처럼 안전하게 처리합니다.',
    checkQuestion: '이 동작이 실제로 무엇을 바꾸나요?',
    codexPromptExample: '필요 없는 클릭은 no-op으로 안전하게 처리되게 해 주세요.',
    category: 'Runtime / Integration',
  },
  {
    id: 'edge-case',
    term: 'Edge Case',
    pronunciation: '엣지 케이스',
    koreanMeaning: '자주 생기지는 않지만 오류를 만들 수 있는 경계 상황',
    simpleMeaning: '끝부분에서 발생하는 특수한 경우입니다.',
    joovisUsage: '검색 결과가 0개일 때 메시지를 보여 주는 것은 edge case 처리입니다.',
    checkQuestion: '빈 목록, 긴 텍스트, 저장 실패 상황은 처리되나요?',
    codexPromptExample: 'Edge case로 검색 결과 0개와 localStorage 실패를 확인해 주세요.',
    category: 'Review / QA',
  },
  {
    id: 'happy-path',
    term: 'Happy Path',
    pronunciation: '해피 패스',
    koreanMeaning: '모든 입력과 조건이 정상일 때의 기본 흐름',
    simpleMeaning: '사용자가 기대대로 사용하는 가장 평범한 길입니다.',
    joovisUsage: '앱 열기, 오늘의 용어 보기, 검색하기, 즐겨찾기 저장이 happy path입니다.',
    checkQuestion: '정상 사용 흐름이 빠르고 분명하게 보이나요?',
    codexPromptExample: 'Happy path를 모바일 화면에서 먼저 완성하고 예외 처리를 더해 주세요.',
    category: 'Review / QA',
  },
  {
    id: 'repro-steps',
    term: 'Repro Steps',
    pronunciation: '리프로 스텝스',
    koreanMeaning: '문제를 다시 재현하기 위한 단계',
    simpleMeaning: '버그를 똑같이 보이게 하는 순서입니다.',
    joovisUsage: '검색이 안 된다면 어떤 단어를 입력했고 어떤 필터였는지 repro steps가 필요합니다.',
    checkQuestion: '다른 사람이 같은 문제를 다시 볼 수 있나요?',
    codexPromptExample: '버그를 고치기 전에 repro steps를 짧게 정리해 주세요.',
    category: 'Review / QA',
  },
  {
    id: 'finding',
    term: 'Finding',
    pronunciation: '파인딩',
    koreanMeaning: '리뷰에서 발견한 문제나 위험',
    simpleMeaning: '고쳐야 할 가능성이 있는 지적 사항입니다.',
    joovisUsage: '카드가 모바일에서 겹치면 review finding으로 남깁니다.',
    checkQuestion: '이 발견은 실제 사용자 영향이 있나요?',
    codexPromptExample: 'Review finding은 파일과 증상을 함께 쓰고 추측만으로 단정하지 마세요.',
    category: 'Review / QA',
  },
  {
    id: 'severity',
    term: 'Severity',
    pronunciation: '시비어리티',
    koreanMeaning: '문제의 심각도',
    simpleMeaning: '얼마나 위험하거나 급한 문제인지 나타냅니다.',
    joovisUsage: '빌드 실패는 높고, 작은 문구 오타는 낮은 severity입니다.',
    checkQuestion: '이 문제가 사용을 막나요, 아니면 개선 사항인가요?',
    codexPromptExample: 'Findings를 severity 순서로 정렬하고 빌드 실패를 최우선으로 다뤄 주세요.',
    category: 'Review / QA',
  },
  {
    id: 'review-thread',
    term: 'Review Thread',
    pronunciation: '리뷰 스레드',
    koreanMeaning: '하나의 코드 리뷰 의견과 그 답변 흐름',
    simpleMeaning: '리뷰 대화 묶음입니다.',
    joovisUsage: '여러 의견이 있으면 각 review thread의 실제 요청을 분리해 처리합니다.',
    checkQuestion: '이 스레드가 요구하는 행동은 무엇인가요?',
    codexPromptExample: 'Review thread마다 actionable한 요청만 뽑아 구현 여부를 표시해 주세요.',
    category: 'Review / QA',
  },
  {
    id: 'test-coverage',
    term: 'Test Coverage',
    pronunciation: '테스트 커버리지',
    koreanMeaning: '테스트가 코드의 어느 범위를 확인하는지 나타내는 정도',
    simpleMeaning: '테스트가 얼마나 넓게 보호하는지 보는 지표입니다.',
    joovisUsage: '이 작은 앱에서는 build와 수동 smoke 확인이 최소 coverage 역할을 합니다.',
    checkQuestion: '위험한 로직을 검증하는 테스트나 확인이 있나요?',
    codexPromptExample: '변경 위험이 크면 test coverage를 늘리고 작으면 build 검증을 우선해 주세요.',
    category: 'Review / QA',
  },
  {
    id: 'typecheck',
    term: 'Typecheck',
    pronunciation: '타입체크',
    koreanMeaning: 'TypeScript 타입 규칙에 맞는지 확인하는 검사',
    simpleMeaning: '값의 형태가 약속과 맞는지 보는 검사입니다.',
    joovisUsage: 'npm run build의 tsc 단계가 이 앱의 typecheck입니다.',
    checkQuestion: '타입 오류 없이 데이터와 컴포넌트가 연결되나요?',
    codexPromptExample: '구현 후 typecheck가 포함된 npm run build를 실행해 주세요.',
    category: 'Review / QA',
  },
  {
    id: 'lint',
    term: 'Lint',
    pronunciation: '린트',
    koreanMeaning: '코드 스타일과 잠재 오류를 자동으로 검사하는 것',
    simpleMeaning: '코드를 깔끔하고 안전하게 보는 검사입니다.',
    joovisUsage: 'Vite scaffold의 lint는 React hook 규칙 등을 확인합니다.',
    checkQuestion: '자동 검사에서 경고나 오류가 남아 있나요?',
    codexPromptExample: 'Lint script가 있으면 실행하고 실패하면 범위 안에서 수정해 주세요.',
    category: 'Review / QA',
  },
  {
    id: 'build',
    term: 'Build',
    pronunciation: '빌드',
    koreanMeaning: '소스 코드를 배포 가능한 정적 파일로 만드는 과정',
    simpleMeaning: '브라우저가 실행할 파일로 묶는 작업입니다.',
    joovisUsage: 'npm run build는 TypeScript와 Vite 번들을 모두 확인합니다.',
    checkQuestion: '배포 가능한 결과물이 실제로 생성되나요?',
    codexPromptExample: '마지막에 npm run build를 실행하고 실패하면 고쳐 주세요.',
    category: 'Git / Change Control',
  },
  {
    id: 'commit',
    term: 'Commit',
    pronunciation: '커밋',
    koreanMeaning: '변경 내용을 버전 관리 기록으로 저장하는 단위',
    simpleMeaning: '작업을 하나의 기록으로 묶는 것입니다.',
    joovisUsage: '작은 기능 단위로 commit하면 변경 이유를 이해하기 쉽습니다.',
    checkQuestion: '이 변경은 하나의 의미 있는 묶음인가요?',
    codexPromptExample: 'Commit은 요청받은 경우에만 만들고 이번 구현 범위만 포함해 주세요.',
    category: 'Git / Change Control',
  },
  {
    id: 'branch',
    term: 'Branch',
    pronunciation: '브랜치',
    koreanMeaning: '버전 관리에서 독립적으로 변경을 진행하는 흐름',
    simpleMeaning: '다른 작업과 분리된 변경 줄기입니다.',
    joovisUsage: '이 새 프로젝트는 기존 JOOVIS repo branch와 관계없이 독립적으로 작업합니다.',
    checkQuestion: '현재 작업이 어떤 branch나 폴더에서 진행되나요?',
    codexPromptExample: 'Branch 상태를 확인하되 현재 workspace 밖 저장소는 접근하지 마세요.',
    category: 'Git / Change Control',
  },
  {
    id: 'pull-request',
    term: 'Pull Request',
    pronunciation: '풀 리퀘스트',
    koreanMeaning: '변경을 검토하고 합치기 위해 올리는 요청',
    simpleMeaning: '코드를 합치기 전 리뷰받는 단위입니다.',
    joovisUsage: '독립 앱 변경은 별도 PR로 다룰 수 있지만 이 작업은 로컬 생성에 집중합니다.',
    checkQuestion: '리뷰어가 이해할 수 있는 변경 설명이 있나요?',
    codexPromptExample: 'Pull request 설명이 필요하면 구현 범위와 검증 결과만 간결하게 적어 주세요.',
    category: 'Git / Change Control',
  },
  {
    id: 'merge-conflict',
    term: 'Merge Conflict',
    pronunciation: '머지 컨플릭트',
    koreanMeaning: '서로 다른 변경이 같은 부분을 바꿔 자동 병합이 안 되는 상태',
    simpleMeaning: '어떤 변경을 살릴지 사람이 골라야 하는 충돌입니다.',
    joovisUsage: '빈 폴더에서 새로 만든 앱은 기존 파일과 merge conflict가 없습니다.',
    checkQuestion: '같은 파일 같은 줄을 여러 변경이 건드렸나요?',
    codexPromptExample: 'Merge conflict가 생기면 양쪽 의도를 읽고 필요한 변경만 남겨 주세요.',
    category: 'Git / Change Control',
  },
  {
    id: 'release-note',
    term: 'Release Note',
    pronunciation: '릴리즈 노트',
    koreanMeaning: '사용자에게 전달할 변경 사항 요약',
    simpleMeaning: '이번 버전에 무엇이 들어갔는지 적은 글입니다.',
    joovisUsage: '이 앱은 문서 생성을 요구하지 않으므로 별도 release note는 만들지 않습니다.',
    checkQuestion: '사용자에게 알려야 할 변경이 있나요?',
    codexPromptExample: 'Release note 파일은 만들지 말고 최종 보고에 구현 기능만 요약해 주세요.',
    category: 'Git / Change Control',
  },
  {
    id: 'changelog',
    term: 'Changelog',
    pronunciation: '체인지로그',
    koreanMeaning: '버전별 변경 이력을 모아 둔 기록',
    simpleMeaning: '무엇이 언제 바뀌었는지 쌓아 둔 목록입니다.',
    joovisUsage: '요청이 없으면 이 작은 독립 앱에는 changelog 파일을 만들지 않습니다.',
    checkQuestion: '변경 이력을 별도 파일로 남길 필요가 있나요?',
    codexPromptExample: 'Changelog는 만들지 말고 final report 형식만 따르세요.',
    category: 'Git / Change Control',
  },
  {
    id: 'feature-flag',
    term: 'Feature Flag',
    pronunciation: '피처 플래그',
    koreanMeaning: '기능을 켜고 끄는 설정 스위치',
    simpleMeaning: '기능 노출을 조절하는 스위치입니다.',
    joovisUsage: '이 앱은 단순 정적 앱이므로 원격 feature flag가 필요 없습니다.',
    checkQuestion: '이 기능은 별도 스위치가 필요한가요?',
    codexPromptExample: 'Feature flag 시스템을 추가하지 말고 요청된 기능을 바로 구현해 주세요.',
    category: 'Runtime / Integration',
  },
  {
    id: 'localstorage',
    term: 'LocalStorage',
    pronunciation: '로컬스토리지',
    koreanMeaning: '브라우저 안에 작은 문자열 데이터를 저장하는 공간',
    simpleMeaning: '기기 브라우저에 즐겨찾기 같은 값을 저장합니다.',
    joovisUsage: '즐겨찾기와 review status는 localStorage에만 저장됩니다.',
    checkQuestion: '이 데이터는 로컬 기기 안에만 있어도 되나요?',
    codexPromptExample: 'Favorites와 review status는 localStorage만 사용하고 동기화는 만들지 마세요.',
    category: 'Runtime / Integration',
  },
  {
    id: 'service-worker',
    term: 'Service Worker',
    pronunciation: '서비스 워커',
    koreanMeaning: '브라우저가 캐시와 오프라인 동작을 돕는 스크립트',
    simpleMeaning: 'PWA 설치와 오프라인 실행을 돕는 브라우저 기능입니다.',
    joovisUsage: 'public/service-worker.js는 정적 파일 캐시를 담당합니다.',
    checkQuestion: '서비스 워커가 외부 작업을 하거나 알림을 보내지는 않나요?',
    codexPromptExample: 'Service worker는 캐시만 담당하게 하고 push notification은 추가하지 마세요.',
    category: 'Runtime / Integration',
  },
  {
    id: 'manifest',
    term: 'Manifest',
    pronunciation: '매니페스트',
    koreanMeaning: 'PWA 이름, 아이콘, 표시 방식 등을 정의하는 파일',
    simpleMeaning: '홈 화면 설치에 필요한 앱 정보 파일입니다.',
    joovisUsage: 'manifest.webmanifest는 앱 이름을 JOOVIS Terms Cockpit으로 제공합니다.',
    checkQuestion: '앱 이름, 아이콘, display 설정이 manifest에 들어 있나요?',
    codexPromptExample: 'Manifest에 name, short_name, display, theme_color, icons를 넣어 주세요.',
    category: 'Runtime / Integration',
  },
  {
    id: 'installability',
    term: 'Installability',
    pronunciation: '인스톨러빌리티',
    koreanMeaning: '웹앱이 홈 화면에 설치될 수 있는 조건을 만족하는 정도',
    simpleMeaning: '브라우저가 앱처럼 설치할 수 있다고 판단하는 상태입니다.',
    joovisUsage: 'manifest와 service worker가 있으면 Android 홈 화면 설치 조건에 가까워집니다.',
    checkQuestion: 'PWA 설치에 필요한 기본 파일이 모두 있나요?',
    codexPromptExample: 'Installability를 위해 manifest와 service worker를 추가하고 build 결과를 확인해 주세요.',
    category: 'Runtime / Integration',
  },
  {
    id: 'pwa',
    term: 'PWA',
    pronunciation: '피더블유에이',
    koreanMeaning: '설치형 앱처럼 동작할 수 있는 웹앱',
    simpleMeaning: '브라우저 앱이지만 홈 화면에 설치해 쓸 수 있습니다.',
    joovisUsage: 'JOOVIS Terms Cockpit은 Android 홈 화면 설치를 목표로 한 PWA입니다.',
    checkQuestion: '이 웹앱은 설치형 경험에 필요한 최소 조건을 갖췄나요?',
    codexPromptExample: 'PWA 요구사항을 만족하되 네이티브 Android 코드는 만들지 마세요.',
    category: 'JOOVIS-Specific',
  },
  {
    id: 'cockpit',
    term: 'Cockpit',
    pronunciation: '콕핏',
    koreanMeaning: '중요 정보를 한 화면에서 조작하고 확인하는 작업 공간',
    simpleMeaning: '학습 상태와 용어를 빠르게 보는 조종석 같은 화면입니다.',
    joovisUsage: 'Terms Cockpit은 오늘의 용어, 검색, 필터, 복습 상태를 한곳에 모읍니다.',
    checkQuestion: '핵심 행동이 첫 화면에서 바로 가능한가요?',
    codexPromptExample: 'Cockpit처럼 첫 화면에 오늘의 용어와 검색, 필터를 모두 배치해 주세요.',
    category: 'JOOVIS-Specific',
  },
  {
    id: 'learning-loop',
    term: 'Learning Loop',
    pronunciation: '러닝 루프',
    koreanMeaning: '보고, 확인하고, 다시 복습하는 반복 학습 흐름',
    simpleMeaning: '알기와 다시 보기 사이를 반복하는 학습 습관입니다.',
    joovisUsage: 'known과 review_again 버튼은 개인 learning loop를 만듭니다.',
    checkQuestion: '사용자가 다음에 무엇을 복습해야 하는지 표시되나요?',
    codexPromptExample: 'Learning loop를 위해 known/review_again 상태를 localStorage에 저장해 주세요.',
    category: 'JOOVIS-Specific',
  },
  {
    id: 'term-card',
    term: 'Term Card',
    pronunciation: '텀 카드',
    koreanMeaning: '하나의 용어 설명과 복습 조작을 담은 카드',
    simpleMeaning: '단어 하나를 공부하는 최소 화면 단위입니다.',
    joovisUsage: 'TermCard 컴포넌트는 의미, 사용 예, 확인 질문, 프롬프트 예시를 표시합니다.',
    checkQuestion: '카드 하나만 봐도 용어를 이해하고 복습 처리할 수 있나요?',
    codexPromptExample: 'Term card에 모든 필수 필드를 표시하고 모바일에서 읽기 좋게 해 주세요.',
    category: 'JOOVIS-Specific',
  },
  {
    id: 'review-queue',
    term: 'Review Queue',
    pronunciation: '리뷰 큐',
    koreanMeaning: '다시 볼 항목을 모아 둔 목록',
    simpleMeaning: '복습해야 할 것들이 기다리는 줄입니다.',
    joovisUsage: 'review_again 상태인 용어들은 사용자의 review queue 역할을 합니다.',
    checkQuestion: '다시 볼 항목을 구분할 수 있나요?',
    codexPromptExample: 'Review queue를 별도 서버 없이 localStorage 상태로 표현해 주세요.',
    category: 'JOOVIS-Specific',
  },
  {
    id: 'command-hygiene',
    term: 'Command Hygiene',
    pronunciation: '커맨드 하이진',
    koreanMeaning: '명령을 안전하고 재현 가능하게 쓰는 습관',
    simpleMeaning: '명령을 실행하기 전에 위치와 영향을 확인하는 태도입니다.',
    joovisUsage: '현재 폴더 확인 후 npm 명령을 실행하는 것이 command hygiene입니다.',
    checkQuestion: '명령이 어느 폴더에서 무엇을 바꾸는지 분명한가요?',
    codexPromptExample: 'Command hygiene을 지켜 현재 workspace에서만 npm install과 build를 실행해 주세요.',
    category: 'JOOVIS-Specific',
  },
] satisfies DevTerm[]
