import type { DeckId, Difficulty, RawDevTerm } from './types'

type FutureTermSeed = {
  deck: DeckId
  term: string
  pronunciation: string
  koreanMeaning: string
  simpleMeaning: string
  category: string
  difficulty: Difficulty
  mentalModel: string
  whyItMatters: string
  withoutIt: string
  mechanism: string
  realWorkflow: string
  usagePattern: string
  commonPitfall: string
  researchBasis: string
  relatedTerms: string[]
  promptKo: string
  promptEn?: string
}

const codexHarnessSource = 'https://openai.com/index/harness-engineering/'
const codexLoopSource = 'https://openai.com/index/unrolling-the-codex-agent-loop/'
const codexAppSource = 'https://openai.com/index/introducing-the-codex-app/'
const mcpArchitectureSource = 'https://modelcontextprotocol.io/docs/learn/architecture'
const mcpClientSource = 'https://modelcontextprotocol.io/docs/learn/client-concepts'

export const futureTerms = [
  makeFutureTerm({
    deck: 'ai-command',
    term: 'Context Engineering',
    pronunciation: '컨텍스트 엔지니어링',
    koreanMeaning: '모델이 판단할 전체 정보 환경을 설계하고 관리하는 작업',
    simpleMeaning:
      '프롬프트 한 문장뿐 아니라 자료 선택, 순서, 도구 결과, 메모리, 압축과 삭제까지 함께 설계합니다.',
    category: 'AI Command',
    difficulty: 'advanced',
    mentalModel:
      'AI의 책상 위에 어떤 문서와 도구를 어떤 순서로 놓을지 설계하는 일입니다. 책상이 넓어도 불필요한 자료가 쌓이면 핵심을 놓칩니다.',
    whyItMatters:
      '장기 작업에서는 모델 능력보다 현재 context에 무엇이 남아 있는지가 결과를 크게 좌우합니다.',
    withoutIt:
      '관련 없는 로그와 오래된 지시가 쌓여 현재 목표, 금지 경계, 최신 사실이 서로 경쟁하게 됩니다.',
    mechanism:
      '필요한 정보를 검색·생성하고, 중복과 잡음을 처리한 뒤, context window 안에서 우선순위와 수명을 관리합니다.',
    realWorkflow:
      '목표를 고정하고 필요한 파일만 수집한 뒤 현재 사실과 과거 기록을 분리합니다. 긴 기록은 출처를 남긴 채 압축하고 결과를 검증합니다.',
    usagePattern:
      '긴 Codex 작업, 여러 문서 검토, 반복 에이전트 실행처럼 한 번의 프롬프트로 끝나지 않는 작업에 사용합니다.',
    commonPitfall:
      '자료를 많이 넣는 것을 context engineering으로 착각하면 안 됩니다. 관련성, 최신성, 출처, 배치 순서가 핵심입니다.',
    researchBasis:
      '2025 Context Engineering survey는 이를 context retrieval/generation, processing, management와 RAG·memory·tool-integrated systems를 포괄하는 분야로 정리했습니다. https://arxiv.org/abs/2507.13334',
    relatedTerms: ['Context Window', 'Context Packing', 'Context Compaction', 'Grounding'],
    promptKo:
      '이 작업의 context를 목표, 최신 사실, 변경 금지 경계, 필요한 도구 결과, 버려도 되는 과거 정보로 나눠 설계해줘.',
    promptEn:
      'Engineer the context by separating the goal, current facts, forbidden boundaries, required tool results, and stale information that can be dropped.',
  }),
  makeFutureTerm({
    deck: 'ai-command',
    term: 'Context Window',
    pronunciation: '컨텍스트 윈도우',
    koreanMeaning: '모델이 한 번의 추론에서 참고할 수 있는 입력과 출력의 작업 공간',
    simpleMeaning: '대화, 지시, 파일 내용, 도구 결과가 함께 들어가는 제한된 기억 공간입니다.',
    category: 'AI Command',
    difficulty: 'intermediate',
    mentalModel:
      '책상 크기와 같습니다. 큰 책상도 자료 배치가 나쁘면 필요한 쪽지를 찾지 못하고, 새 자료가 들어오면 오래된 자료가 밀려날 수 있습니다.',
    whyItMatters: '공간의 크기와 실제로 잘 활용되는 길이는 같지 않으며, 입력과 출력도 같은 예산을 나눠 씁니다.',
    withoutIt: '긴 자료를 무작정 붙여 넣다가 핵심 지시가 묻히거나 출력 공간이 부족해질 수 있습니다.',
    mechanism:
      '텍스트와 도구 결과는 토큰으로 변환되어 제한된 창에 배치되고, 모델은 그 안의 관계를 바탕으로 다음 출력을 계산합니다.',
    realWorkflow:
      '자료 길이를 확인하고 핵심 지시는 짧고 명확하게 유지합니다. 오래된 로그는 요약하고 원문 위치를 남깁니다.',
    usagePattern: '긴 보고서, 대형 코드베이스, 장기 대화에서 정보량과 배치 전략을 정할 때 사용합니다.',
    commonPitfall: '표시된 최대 길이가 모든 위치의 정보를 똑같이 잘 활용한다는 뜻은 아닙니다.',
    researchBasis:
      '장문맥 연구는 모델이 긴 입력의 모든 위치를 균등하게 활용하지 못할 수 있음을 반복해 보고했습니다. https://aclanthology.org/2024.tacl-1.9/',
    relatedTerms: ['Context Engineering', 'Lost in the Middle', 'Context Packing', 'Token Budget'],
    promptKo:
      'context window를 낭비하는 중복과 오래된 정보를 찾고, 핵심 지시와 근거가 잘 보이도록 재배치해줘.',
    promptEn:
      'Identify duplicate or stale context, then reorder the essential instructions and evidence so they remain easy to use within the context window.',
  }),
  makeFutureTerm({
    deck: 'ai-command',
    term: 'Lost in the Middle',
    pronunciation: '로스트 인 더 미들',
    koreanMeaning: '긴 입력의 중간에 있는 핵심 정보를 모델이 덜 활용하는 현상',
    simpleMeaning: '중요한 내용이 문서 가운데 묻히면 처음이나 끝에 있을 때보다 놓칠 수 있다는 문제입니다.',
    category: 'Prompt Quality',
    difficulty: 'advanced',
    mentalModel:
      '긴 회의에서 첫 발언과 마지막 결론은 기억하지만 중간의 중요한 조건은 흐려지는 것과 비슷합니다.',
    whyItMatters: '긴 context를 지원하는 모델도 정보 위치에 따라 검색과 추론 성능이 달라질 수 있습니다.',
    withoutIt: '자료를 한 덩어리로 넣고도 모델이 모든 조건을 동일하게 읽었다고 잘못 믿게 됩니다.',
    mechanism:
      '긴 입력에서 위치 편향과 주의 분산이 생기면 중간 구간의 관련 정보가 최종 판단에 약하게 반영될 수 있습니다.',
    realWorkflow:
      '핵심 조건을 앞쪽에 요약하고, 원문 구간을 명시하며, 마지막에 검증 체크리스트로 다시 고정합니다.',
    usagePattern: '긴 사양서, 판결문, 로그 묶음, 대규모 diff를 AI에게 검토시킬 때 고려합니다.',
    commonPitfall: '같은 내용을 무조건 앞뒤에 반복하면 오히려 잡음이 늘 수 있습니다. 요약과 출처 연결이 필요합니다.',
    researchBasis:
      'Liu et al.은 관련 정보가 긴 입력의 시작이나 끝보다 중간에 있을 때 성능이 낮아질 수 있음을 보고했습니다. https://arxiv.org/abs/2307.03172',
    relatedTerms: ['Context Window', 'Context Packing', 'Reference Text Grounding', 'Verifier Pass'],
    promptKo:
      '긴 자료의 핵심 조건을 먼저 요약하고 원문 위치를 붙인 뒤, 답변 전에 빠뜨린 중간 조건이 없는지 검증해줘.',
    promptEn:
      'Summarize the critical constraints with source locations first, then verify that no important middle-context condition was missed.',
  }),
  makeFutureTerm({
    deck: 'ai-command',
    term: 'Agent Loop',
    pronunciation: '에이전트 루프',
    koreanMeaning: '모델이 판단, 도구 실행, 관찰, 다음 판단을 반복하는 실행 순환',
    simpleMeaning: 'AI가 한 번 답하고 끝나는 대신 결과를 확인하며 여러 단계로 작업하는 기본 구조입니다.',
    category: 'AI Command',
    difficulty: 'advanced',
    mentalModel: '운전자가 보고, 조작하고, 계기판을 다시 확인하는 순환과 같습니다.',
    whyItMatters: '코드 수정이나 조사처럼 외부 상태가 바뀌는 작업은 한 번의 텍스트 생성만으로 완결되지 않습니다.',
    withoutIt: '도구 결과를 다음 판단에 반영하지 못해 추측을 계속하거나 완료 조건 없이 반복할 수 있습니다.',
    mechanism:
      '모델 추론이 도구 호출을 만들고, harness가 도구를 실행해 관찰을 돌려주며, 모델은 종료 조건까지 이 과정을 반복합니다.',
    realWorkflow:
      '목표와 종료 조건을 정하고 읽기 도구로 상태를 확인합니다. 작은 변경을 실행한 뒤 테스트 결과를 관찰해 다음 행동을 결정합니다.',
    usagePattern: 'Codex, 조사 에이전트, 도구 사용형 AI의 실제 행동을 이해하고 지시할 때 사용합니다.',
    commonPitfall: '반복 횟수와 중단 조건이 없으면 비용이 늘거나 같은 실패를 되풀이할 수 있습니다.',
    researchBasis: `OpenAI는 Codex harness의 핵심 실행 논리를 model과 tools 사이의 agent loop로 설명합니다. ${codexLoopSource}`,
    relatedTerms: ['Harness Engineering', 'Tool-Augmented Prompting', 'Stop Condition', 'Execution Trace'],
    promptKo:
      '확인 → 최소 행동 → 결과 관찰 → 다음 판단 순서로 진행하고, 완료 조건이나 동일 실패 2회에서 멈춰줘.',
    promptEn:
      'Use an inspect-act-observe loop, and stop when the acceptance criteria are met or the same failure repeats twice.',
  }),
  makeFutureTerm({
    deck: 'ai-command',
    term: 'Harness Engineering',
    pronunciation: '하네스 엔지니어링',
    koreanMeaning: 'AI가 안정적으로 일하도록 도구, 지시, 환경, 검증 루프를 설계하는 작업',
    simpleMeaning: '모델에게 더 세게 말하는 대신 좋은 일을 할 수 있는 작업장을 만들어 주는 방식입니다.',
    category: 'AI Command',
    difficulty: 'advanced',
    mentalModel: '숙련자에게도 계측기, 안전장치, 작업 순서, 품질 검사가 필요한 생산 라인을 설계하는 일과 같습니다.',
    whyItMatters: '같은 모델도 도구 가시성, 저장소 구조, 테스트 피드백, 경계 집행 방식에 따라 결과가 크게 달라집니다.',
    withoutIt: '프롬프트를 길게 고치는 데만 매달리고 실제로 부족한 도구, 문서, 테스트, 복구 경로를 놓칩니다.',
    mechanism:
      '목표를 에이전트가 읽을 수 있게 만들고, 필요한 능력을 도구로 제공하며, 규칙을 자동 검사로 집행하고, 실패를 다음 개선 입력으로 되돌립니다.',
    realWorkflow:
      '반복 실패를 모델 탓으로 끝내지 않고 누락된 능력을 찾습니다. 관련 문서, 도구, 테스트, 관찰 가능성을 추가해 같은 실패가 재발하는지 측정합니다.',
    usagePattern: '장기 Codex 작업, 팀 단위 에이전트 사용, 반복 자동화의 품질을 높일 때 사용합니다.',
    commonPitfall: '규칙을 많이 쓰는 것 자체가 하네스는 아닙니다. 규칙이 에이전트에게 보이고 실제 검사로 집행되어야 합니다.',
    researchBasis: `OpenAI의 2026 harness engineering 사례는 인간이 의도를 명시하고 환경·도구·피드백 루프를 설계하는 역할로 이동했다고 설명합니다. ${codexHarnessSource}`,
    relatedTerms: ['Agent Loop', 'Deterministic Verification', 'Feedback Loop', 'Capability State'],
    promptKo:
      '모델에게 다시 시도시키기 전에 부족한 도구, 문서, 경계, 테스트, 피드백 루프를 찾아 하네스 개선안으로 제시해줘.',
    promptEn:
      'Before retrying, identify the missing tools, documentation, boundaries, tests, or feedback loops and propose a harness improvement.',
  }),
  makeFutureTerm({
    deck: 'ai-command',
    term: 'Eval-driven Development',
    pronunciation: '이밸 드리븐 디벨롭먼트',
    koreanMeaning: '대표 평가 사례와 실패 기준을 먼저 만들고 AI 동작을 개선하는 방식',
    simpleMeaning: '좋아 보이는 답이 아니라 반복 측정 가능한 사례로 AI 품질을 올립니다.',
    category: 'Review / QA',
    difficulty: 'advanced',
    mentalModel: '운전 연습 전에 실제 도로 상황을 대표하는 시험 코스를 만드는 것과 같습니다.',
    whyItMatters: 'AI 출력은 확률적이어서 한 번 잘된 사례만으로 안정성을 판단할 수 없습니다.',
    withoutIt: '프롬프트를 바꿀 때 무엇이 좋아지고 무엇이 퇴보했는지 감으로 판단하게 됩니다.',
    mechanism:
      '대표 입력, 기대 기준, 채점 방법, 실패 사례를 고정하고 변경 전후 결과를 같은 조건에서 비교합니다.',
    realWorkflow:
      '실제 실패를 작은 eval 사례로 보존하고 기준선을 측정합니다. 지시나 하네스를 바꾼 뒤 통과율과 새 회귀를 확인합니다.',
    usagePattern: '프롬프트, 에이전트 도구, 분류·추출 흐름을 반복 개선할 때 사용합니다.',
    commonPitfall: '평가 세트가 실제 사용을 대표하지 않거나 모델이 평가 사례에 과적합되면 숫자만 좋아질 수 있습니다.',
    researchBasis:
      'OpenAI의 agent guidance는 성능 기준선을 세우기 위해 evals를 먼저 구축하고 실제 edge case를 평가 루프에 반영할 것을 권합니다. https://openai.com/business/guides-and-resources/a-practical-guide-to-building-ai-agents/',
    relatedTerms: ['Rubric', 'Prompt Regression Test', 'Execution-based Evaluation', 'Judge Bias'],
    promptKo:
      '대표 성공 3개와 실패 3개를 eval 사례로 만들고, 판정 기준과 변경 전 기준선을 먼저 정해줘.',
    promptEn:
      'Create three representative success cases and three failure cases, define the grading rubric, and establish a baseline before changing the prompt.',
  }),
  makeFutureTerm({
    deck: 'ai-command',
    term: 'Execution Trace',
    pronunciation: '엑시큐션 트레이스',
    koreanMeaning: '에이전트가 어떤 판단과 도구 호출을 거쳐 결과에 도달했는지 남긴 실행 기록',
    simpleMeaning: '최종 답만 보지 않고 어떤 행동이 어떤 결과를 만들었는지 따라가는 기록입니다.',
    category: 'Review / QA',
    difficulty: 'intermediate',
    mentalModel: '택배의 이동 경로처럼 요청이 어느 단계와 도구를 거쳤는지 시간순으로 보는 지도입니다.',
    whyItMatters: '최종 답이 틀렸을 때 모델 판단, 도구 입력, 도구 결과, 종료 조건 중 원인을 분리할 수 있습니다.',
    withoutIt: '결과가 실패했다는 사실만 알고 어느 단계에서 바로잡아야 하는지 찾기 어렵습니다.',
    mechanism: '각 모델 호출, 도구 호출, 입력·출력, 오류, handoff와 시간을 연결된 span으로 기록합니다.',
    realWorkflow: '실패한 실행을 열어 최초의 잘못된 결정 지점을 찾고, 그 앞의 context와 도구 결과를 확인합니다.',
    usagePattern: '도구 사용 에이전트 디버깅, 지연·비용 분석, eval 실패 원인 분류에 사용합니다.',
    commonPitfall: 'trace에 민감한 입력이나 비밀값을 그대로 남기지 말고 보존 기간과 접근 권한을 정해야 합니다.',
    researchBasis:
      'OpenAI Agents SDK는 agent execution을 시각화해 디버깅하고 최적화하기 위한 tracing과 observability를 핵심 기능으로 설명합니다. https://openai.com/index/new-tools-for-building-agents/',
    relatedTerms: ['Agent Loop', 'Telemetry', 'Audit Trail', 'Eval-driven Development'],
    promptKo:
      '최종 답만 평가하지 말고 도구 호출 순서, 관찰 결과, 최초 실패 지점, 불필요한 반복을 trace 기준으로 분석해줘.',
    promptEn:
      'Evaluate the execution trace, including tool-call order, observations, the first failure point, and unnecessary repetition.',
  }),
  makeFutureTerm({
    deck: 'ai-command',
    term: 'Long-Horizon Task',
    pronunciation: '롱 호라이즌 태스크',
    koreanMeaning: '많은 단계와 긴 시간 동안 상태를 유지해야 완료되는 작업',
    simpleMeaning: '여러 파일 수정, 반복 검증, 중간 복구가 필요한 장기 작업입니다.',
    category: 'AI Command',
    difficulty: 'advanced',
    mentalModel: '짧은 심부름이 아니라 여러 날 이어지는 공사처럼 중간 기준점과 인수인계 기록이 필요한 일입니다.',
    whyItMatters: '작업이 길수록 목표 이탈, context 손실, 누적 오류, 중복 작업 위험이 커집니다.',
    withoutIt: '짧은 질의처럼 맡겨 놓고 중간 산출물, checkpoint, 복구 계획 없이 끝까지 진행하게 됩니다.',
    mechanism: '큰 목표를 검증 가능한 단계로 나누고 각 단계의 상태를 외부 기록에 남겨 다음 반복이 이어받게 합니다.',
    realWorkflow: 'WBS를 만들고 단계별 acceptance criteria와 checkpoint를 둡니다. 실패하면 마지막 검증 지점으로 돌아갑니다.',
    usagePattern: '대규모 리팩터링, 마이그레이션, 긴 조사, 다중 에이전트 작업에 사용합니다.',
    commonPitfall: '한 프롬프트에 모든 일을 넣고 중간 검증 없이 자율성만 높이는 것은 장기 작업 설계가 아닙니다.',
    researchBasis:
      'OpenAI는 최신 Codex 작업을 복잡한 장기 작업과 다중 에이전트 감독의 문제로 설명하며, checkpoint와 feedback 환경의 중요성을 강조합니다. https://openai.com/index/introducing-gpt-5-2-codex/',
    relatedTerms: ['WBS', 'Checkpoint', 'Context Compaction', 'Agent Supervision'],
    promptKo:
      '이 장기 작업을 검증 가능한 단계로 나누고 각 단계의 완료 기준, 저장할 상태, 실패 시 복귀 지점을 정해줘.',
    promptEn:
      'Break this long-horizon task into verifiable stages, with completion criteria, persisted state, and a rollback checkpoint for each stage.',
  }),
  makeFutureTerm({
    deck: 'ai-command',
    term: 'LLM-as-a-Judge',
    pronunciation: '엘엘엠 애즈 어 저지',
    koreanMeaning: '언어모델이 다른 답변의 품질을 기준표로 평가하는 방식',
    simpleMeaning: '사람이 매번 읽기 어려운 많은 결과를 AI 심사자가 채점하게 합니다.',
    category: 'Review / QA',
    difficulty: 'advanced',
    mentalModel: '답을 만드는 선수와 점수를 매기는 심판을 분리하되 심판도 오판할 수 있다고 보는 구조입니다.',
    whyItMatters: '자유 형식 답변은 문자열 일치로 평가하기 어려워 의미·근거·형식을 함께 볼 심사 방식이 필요합니다.',
    withoutIt: '대규모 평가가 어렵지만, 반대로 AI 심판을 맹신하면 체계적인 편향이 숫자로 포장될 수 있습니다.',
    mechanism: '평가 기준과 입력·후보 답변을 심사 모델에 주고 점수, 판정, 짧은 근거를 구조화해 받습니다.',
    realWorkflow: '사람이 검증한 표본으로 심사 기준을 보정하고 후보 순서를 바꿔 재평가하며 불일치를 추적합니다.',
    usagePattern: '요약, 글쓰기, 지시 준수처럼 하나의 정답이 없는 출력 평가에 사용합니다.',
    commonPitfall: '위치 편향, 길이 편향, 자기 선호, 기준 불명확성 때문에 단일 심사 결과를 진실처럼 쓰면 안 됩니다.',
    researchBasis:
      'LLM-as-a-Judge는 확장 가능한 평가 방식이지만 위치 편향 등 체계적 오류가 보고되어 인간 표본과 보정이 필요합니다. https://arxiv.org/abs/2406.07791',
    relatedTerms: ['Judge Bias', 'Rubric', 'Answer Calibration', 'Quality Control Sample'],
    promptKo:
      '이 답을 루브릭별로 평가하되 후보 순서를 바꿔 한 번 더 판정하고, 두 결과가 다르면 사람 검토로 넘겨줘.',
    promptEn:
      'Grade this answer against the rubric, repeat with candidate order reversed, and escalate disagreements for human review.',
  }),
  makeFutureTerm({
    deck: 'ai-command',
    term: 'Judge Bias',
    pronunciation: '저지 바이어스',
    koreanMeaning: 'AI 심사 결과가 내용 외의 위치, 길이, 표현 방식 등에 체계적으로 치우치는 현상',
    simpleMeaning: 'AI가 평가자 역할을 할 때도 반복되는 편견과 오판 패턴이 생길 수 있습니다.',
    category: 'Review / QA',
    difficulty: 'advanced',
    mentalModel: '같은 답도 먼저 읽었는지, 더 길게 썼는지에 따라 점수가 달라지는 불안정한 심판과 같습니다.',
    whyItMatters: '평가 모델의 높은 확신이 평가의 정확성을 보장하지 않습니다.',
    withoutIt: '작은 모델 차이보다 심사 편향이 더 큰데도 순위와 품질 차이를 확정할 수 있습니다.',
    mechanism: '후보 위치, 답변 길이, 문체, 모델 정체성 같은 비본질 신호가 심사 판단에 영향을 줍니다.',
    realWorkflow: '후보 순서를 교환하고 여러 심사자·사람 표본과 비교해 일관성, 위치 안정성, 보정 오차를 측정합니다.',
    usagePattern: 'LLM 기반 eval, 답변 비교, 자동 리뷰의 신뢰도를 검토할 때 사용합니다.',
    commonPitfall: '심사 호출 수만 늘리면 같은 방향의 체계적 편향은 사라지지 않을 수 있습니다.',
    researchBasis:
      '2024 position-bias 연구는 여러 LLM judge에서 후보 위치에 따른 체계적 편향을 확인했습니다. https://arxiv.org/abs/2406.07791',
    relatedTerms: ['LLM-as-a-Judge', 'Counterexample', 'Quality Control Sample', 'Human-in-the-loop'],
    promptKo:
      '심사 결과의 위치 편향, 길이 편향, 기준 누락 가능성을 검사하고 사람이 확인할 표본을 분리해줘.',
    promptEn:
      'Check the judgment for position bias, verbosity bias, and rubric omissions, then select a sample for human validation.',
  }),
  makeFutureTerm({
    deck: 'ai-command',
    term: 'Context Compaction',
    pronunciation: '컨텍스트 컴팩션',
    koreanMeaning: '긴 작업 기록을 핵심 상태와 근거 중심으로 압축해 다음 단계에 넘기는 처리',
    simpleMeaning: '대화를 잘라 버리지 않고 계속 일하는 데 필요한 상태만 작은 패킷으로 다시 만듭니다.',
    category: 'AI Command',
    difficulty: 'advanced',
    mentalModel: '긴 항해 일지를 현재 위치, 결정, 위험, 다음 목적지만 남긴 교대 보고서로 바꾸는 일입니다.',
    whyItMatters: '장기 작업은 context window를 넘기 쉬우며 오래된 시행착오가 최신 상태를 가릴 수 있습니다.',
    withoutIt: '기록이 잘리며 중요한 경계와 결정이 사라지거나, 모든 기록을 유지해 주의가 분산됩니다.',
    mechanism: '현재 목표, 완료 사항, 열린 문제, 변경 파일, 검증 결과, 금지 경계를 추출하고 원문 참조를 남깁니다.',
    realWorkflow: '단계 종료마다 state capsule을 만들고 다음 실행이 원문을 다시 찾을 수 있도록 파일과 근거 위치를 적습니다.',
    usagePattern: '긴 Codex 세션, agent handoff, 여러 날 이어지는 조사와 구현에 사용합니다.',
    commonPitfall: '압축문만 source of truth로 삼으면 요약 오염이 누적될 수 있으므로 원문과 검증 포인트를 함께 보존합니다.',
    researchBasis:
      'OpenAI는 장기 Codex 작업에서 task-relevant context를 보존하는 native compaction을 핵심 개선점으로 설명합니다. https://openai.com/index/introducing-gpt-5-2-codex/',
    relatedTerms: ['Context Compression', 'State Capsule', 'Handoff Packet', 'Source of Truth'],
    promptKo:
      '현재 목표, 완료 사항, 열린 문제, 변경 파일, 검증 결과, 금지 경계를 state capsule로 압축하고 원문 위치를 남겨줘.',
    promptEn:
      'Compact the current goal, completed work, open issues, changed files, validation results, and forbidden boundaries into a state capsule with source locations.',
  }),
  makeFutureTerm({
    deck: 'ai-command',
    term: 'Agent Supervision',
    pronunciation: '에이전트 슈퍼비전',
    koreanMeaning: '여러 에이전트의 목표, 진행, 위험, 결과를 사람이 감독하는 운영 방식',
    simpleMeaning: '사람이 모든 코드를 직접 쓰기보다 일을 나누고 중간 결과와 위험한 행동을 통제합니다.',
    category: 'AI Command',
    difficulty: 'advanced',
    mentalModel: '여러 작업반을 직접 대신 일하지 않고 작업 구역, 검사 시점, 인수 기준으로 관리하는 현장 감독과 같습니다.',
    whyItMatters: '병렬 에이전트는 처리량을 높이지만 중복, 충돌, 목표 이탈, 검토 부담도 함께 키웁니다.',
    withoutIt: '여러 작업이 같은 파일을 건드리거나 검증되지 않은 결과가 다음 단계의 사실로 굳어질 수 있습니다.',
    mechanism: '작업을 독립 범위로 나누고 각 에이전트의 상태, diff, 검증 결과, escalation을 한곳에서 비교합니다.',
    realWorkflow: '작업별 소유 범위를 정하고 독립 환경에서 실행합니다. 결과는 공통 acceptance criteria로 검토한 뒤 통합합니다.',
    usagePattern: '여러 Codex thread, 병렬 조사, 팀 단위 agent workflow를 운영할 때 사용합니다.',
    commonPitfall: '에이전트 수를 늘리는 것이 곧 성능 향상은 아닙니다. 작업 독립성과 통합 비용을 먼저 봐야 합니다.',
    researchBasis: `OpenAI Codex app은 별도 프로젝트 thread와 worktree에서 여러 agent를 병렬로 운영하고 사람이 diff를 감독하는 흐름을 설명합니다. ${codexAppSource}`,
    relatedTerms: ['Orchestration', 'Worktree Isolation', 'Handoff', 'Review Gate'],
    promptKo:
      '작업을 충돌 없는 독립 범위로 나누고 각 에이전트의 소유 파일, 완료 기준, 검토 지점을 표로 정리해줘.',
    promptEn:
      'Split the work into conflict-free scopes and list each agent’s owned files, completion criteria, and review checkpoint.',
  }),
  makeFutureTerm({
    deck: 'development',
    term: 'Deterministic Verification',
    pronunciation: '디터미니스틱 베리피케이션',
    koreanMeaning: '같은 입력과 상태에서 언제나 같은 통과·실패를 내는 자동 검증',
    simpleMeaning: 'AI의 자기평가 대신 테스트, 타입 검사, 스키마 검사처럼 재실행 가능한 판정으로 확인합니다.',
    category: 'Review / QA',
    difficulty: 'intermediate',
    mentalModel: '감독자의 기분이 아니라 같은 치수에서 늘 같은 결과를 내는 계측기와 같습니다.',
    whyItMatters: '확률적인 생성 결과를 안정적으로 운영하려면 마지막 판정만큼은 반복 가능해야 합니다.',
    withoutIt: 'AI가 “문제없다”고 말한 것을 검증으로 착각하거나 실행할 때마다 판정이 달라질 수 있습니다.',
    mechanism: '명시된 입력을 실행해 exit code, assertion, schema, 파일 diff 같은 기계 판정값을 비교합니다.',
    realWorkflow: 'acceptance criteria를 테스트 가능한 조건으로 바꾸고 구현 전 실패, 구현 후 성공, 회귀 없음 순서로 확인합니다.',
    usagePattern: 'AI 생성 코드, 데이터 변환, 배포 산출물, 반복 에이전트 작업 검증에 사용합니다.',
    commonPitfall: '테스트가 잘못된 요구를 고정할 수도 있으므로 판정 조건 자체도 리뷰해야 합니다.',
    researchBasis: `OpenAI harness engineering 사례는 validation과 feedback을 저장소 안에 집행 가능한 형태로 인코딩하는 것을 강조합니다. ${codexHarnessSource}`,
    relatedTerms: ['Checker', 'Acceptance Criteria', 'Execution-based Evaluation', 'Regression'],
    promptKo:
      '완료 주장을 믿지 말고 같은 상태에서 재실행 가능한 테스트, 타입 검사, 빌드 결과로 판정해줘.',
  }),
  makeFutureTerm({
    deck: 'development',
    term: 'Worktree Isolation',
    pronunciation: '워크트리 아이솔레이션',
    koreanMeaning: 'Git 작업 트리를 분리해 여러 작업이 같은 파일 상태를 충돌 없이 다루게 하는 방식',
    simpleMeaning: '각 작업자가 같은 저장소의 독립된 작업 공간에서 변경하도록 만듭니다.',
    category: 'Git / Change Control',
    difficulty: 'intermediate',
    mentalModel: '같은 설계도를 쓰되 각 팀이 독립된 작업대에서 시제품을 만드는 것과 같습니다.',
    whyItMatters: '병렬 작업에서 한 작업의 미완성 변경이 다른 작업의 검사와 diff를 오염시키는 것을 줄입니다.',
    withoutIt: '여러 에이전트나 사람이 같은 working tree를 건드려 파일 충돌과 검증 혼선이 생길 수 있습니다.',
    mechanism: 'Git이 하나의 object database를 공유하면서 branch별 checkout 디렉터리와 index를 따로 유지합니다.',
    realWorkflow: '작업마다 branch와 worktree를 만들고 그 안에서만 수정·검증한 뒤 diff나 commit 단위로 통합합니다.',
    usagePattern: '여러 Codex 작업을 병렬로 진행하거나 큰 변경을 안전하게 실험할 때 사용합니다.',
    commonPitfall: '격리는 자동 병합을 보장하지 않으며 같은 논리 영역을 바꾸면 통합 충돌은 여전히 생깁니다.',
    researchBasis: `OpenAI Codex app은 각 agent가 isolated copy에서 작업하도록 worktree 지원을 제공한다고 설명합니다. ${codexAppSource}`,
    relatedTerms: ['Branch', 'Merge Conflict', 'Agent Supervision', 'Sandbox'],
    promptKo: '이 작업을 독립 worktree에서 수행하고 사용자 working tree의 미완성 변경은 건드리지 마.',
  }),
  makeFutureTerm({
    deck: 'development',
    term: 'Feedback Loop',
    pronunciation: '피드백 루프',
    koreanMeaning: '실행 결과와 실패를 다음 작업 개선의 입력으로 되돌리는 순환',
    simpleMeaning: '실패를 보고 끝내지 않고 다시 같은 실패가 나지 않도록 환경과 규칙을 고칩니다.',
    category: 'Architecture',
    difficulty: 'intermediate',
    mentalModel: '온도계가 측정한 값을 난방 제어기에 돌려보내 목표 온도에 맞추는 구조와 같습니다.',
    whyItMatters: '에이전트와 소프트웨어는 실제 결과를 관찰해야 계획과 현실의 차이를 줄일 수 있습니다.',
    withoutIt: '같은 오류를 다른 표현으로 반복하고 사람이 매번 수동으로 바로잡게 됩니다.',
    mechanism: '행동의 결과를 측정하고 목표와의 오차를 분류해 다음 지시, 도구, 테스트, 코드 변경에 반영합니다.',
    realWorkflow: '실패를 재현하고 최초 원인을 기록한 뒤 자동 검사나 문서를 보강합니다. 같은 사례로 재실행해 개선 여부를 확인합니다.',
    usagePattern: 'CI, 모니터링, 사용자 피드백, 에이전트 하네스 개선에 사용합니다.',
    commonPitfall: '측정값이 잘못됐거나 피드백이 너무 늦으면 시스템이 엉뚱한 방향으로 최적화될 수 있습니다.',
    researchBasis: `OpenAI harness engineering 사례는 실패에서 누락된 capability를 찾아 저장소와 검증 환경에 되먹임하는 방식을 설명합니다. ${codexHarnessSource}`,
    relatedTerms: ['Telemetry', 'Regression', 'Harness Engineering', 'Drift Monitor'],
    promptKo:
      '이번 실패를 일회성 수정으로 끝내지 말고, 같은 실패를 잡을 테스트·문서·가드를 피드백 루프에 추가해줘.',
  }),
  makeFutureTerm({
    deck: 'development',
    term: 'Execution-based Evaluation',
    pronunciation: '엑시큐션 베이스드 이밸류에이션',
    koreanMeaning: '설명이나 코드 모양이 아니라 실제 실행 결과로 품질을 판정하는 평가',
    simpleMeaning: '코드를 실행하고 테스트를 통과하는지 확인해 AI 작업 결과를 평가합니다.',
    category: 'Review / QA',
    difficulty: 'advanced',
    mentalModel: '요리법의 문장이 그럴듯한지보다 실제로 요리해 결과를 확인하는 시험과 같습니다.',
    whyItMatters: '코드는 자연어 설명과 달리 실행 의미가 있으며 작은 누락도 실제 실패로 드러납니다.',
    withoutIt: '보기 좋은 diff와 자신감 있는 설명을 기능이 맞다는 증거로 착각할 수 있습니다.',
    mechanism: '고정된 환경에서 코드를 실행하고 테스트, 출력, 부작용, 성능 조건을 기대값과 비교합니다.',
    realWorkflow: '재현 가능한 환경과 fixture를 준비하고 실패 테스트를 먼저 확인한 뒤 패치 전후 결과를 비교합니다.',
    usagePattern: '코딩 agent benchmark, 자동 코드 리뷰, 리팩터링·버그 수정 검증에 사용합니다.',
    commonPitfall: '테스트가 좁으면 정답을 하드코딩해 통과할 수 있으므로 숨은 사례와 회귀 검사가 필요합니다.',
    researchBasis:
      'SWE-bench 계열 평가는 실제 저장소에서 테스트 실행으로 agent의 문제 해결 여부를 판정합니다. https://arxiv.org/abs/2310.06770',
    relatedTerms: ['Deterministic Verification', 'Fixture', 'Regression', 'Benchmark Contamination'],
    promptKo: '설명 품질이 아니라 재현 절차와 실행 테스트 결과로 변경을 판정해줘.',
  }),
  makeFutureTerm({
    deck: 'development',
    term: 'Benchmark Contamination',
    pronunciation: '벤치마크 컨태미네이션',
    koreanMeaning: '평가 문제나 정답 정보가 학습·개발 과정에 섞여 성능이 부풀려지는 현상',
    simpleMeaning: '모델이 문제 해결 능력보다 이미 본 문제를 기억해 높은 점수를 받을 수 있는 위험입니다.',
    category: 'Review / QA',
    difficulty: 'advanced',
    mentalModel: '시험 문제가 사전에 유출되어 점수는 높지만 실제 실력은 알 수 없는 상황과 같습니다.',
    whyItMatters: '정적 공개 벤치마크는 시간이 지날수록 모델·도구·프롬프트가 평가 사례에 맞춰질 가능성이 커집니다.',
    withoutIt: '벤치마크 상승을 실제 사용자 작업 향상으로 그대로 해석할 수 있습니다.',
    mechanism: '평가 사례 또는 매우 유사한 패턴이 학습 데이터, 프롬프트 템플릿, 도구 규칙에 노출되어 독립 평가가 깨집니다.',
    realWorkflow: '최신 비공개·시간 분리 사례를 사용하고 중복 검색, mutation test, 실제 사용자형 질의로 재평가합니다.',
    usagePattern: '모델·agent benchmark 결과를 읽거나 자체 eval 세트를 운영할 때 사용합니다.',
    commonPitfall: '출처가 공개됐다는 이유만으로 모든 성능이 오염됐다고 단정할 수는 없습니다. 별도 검사가 필요합니다.',
    researchBasis:
      'SWE-rebench는 정적 benchmark의 오염 위험을 줄이기 위해 지속적으로 최신 작업을 수집하는 평가 파이프라인을 제안했습니다. https://arxiv.org/abs/2505.20411',
    relatedTerms: ['Eval-driven Development', 'Execution-based Evaluation', 'Regression', 'Provenance'],
    promptKo: '이 평가 결과에서 데이터 오염, 공개 문제 과적합, 실제 사용자 질의와의 차이를 분리해 검토해줘.',
  }),
  ...makeEmergingTerms(),
  ...makeMcpTerms(),
] satisfies RawDevTerm[]

function makeEmergingTerms(): RawDevTerm[] {
  return [
    makeFutureTerm({
      deck: 'ai-command',
      term: 'Evals',
      pronunciation: '이밸즈',
      koreanMeaning: 'AI 시스템의 동작을 대표 사례와 판정 기준으로 반복 측정하는 평가 체계',
      simpleMeaning: '프롬프트나 모델을 바꿨을 때 실제 품질이 좋아졌는지 같은 시험지로 비교합니다.',
      category: 'Review / QA',
      difficulty: 'intermediate',
      mentalModel: '제품 출고 전 매번 같은 규격으로 성능과 결함을 검사하는 품질 시험대와 같습니다.',
      whyItMatters: '확률적인 AI 출력은 한 번의 성공 사례나 인상만으로 안정성을 판단하기 어렵습니다.',
      withoutIt: '프롬프트를 고칠 때 좋아진 항목과 새로 깨진 항목을 구분하지 못합니다.',
      mechanism: '입력 사례, 기대 특성, grader, 통과 임계값을 고정하고 여러 실행 결과를 수집해 기준선과 비교합니다.',
      realWorkflow: '실제 사용 사례와 실패 사례를 모아 dataset을 만들고 grader를 검증한 뒤 변경 전후 점수와 오류 유형을 비교합니다.',
      usagePattern: '프롬프트, agent, 추출·분류·요약 기능을 출시하거나 회귀를 막을 때 사용합니다.',
      commonPitfall: '평가 사례가 실제 사용을 대표하지 않거나 grader가 틀리면 높은 점수가 잘못된 안심을 줄 수 있습니다.',
      researchBasis: 'OpenAI는 agent 구축에서 eval로 성능 기준선을 만들고 실제 edge case를 반복 평가할 것을 권합니다. https://openai.com/business/guides-and-resources/a-practical-guide-to-building-ai-agents/',
      relatedTerms: ['Eval-driven Development', 'Rubric', 'Prompt Regression Test', 'LLM-as-a-Judge'],
      promptKo: '대표 입력, 기대 결과, 판정 기준, 실패 임계값을 갖춘 작은 eval 세트를 먼저 만들어줘.',
      promptEn: 'Create a small eval set with representative inputs, expected properties, grading criteria, and a failure threshold.',
    }),
    makeFutureTerm({
      deck: 'ai-command',
      term: 'Tool Calling',
      pronunciation: '툴 콜링',
      koreanMeaning: '모델이 구조화된 인자로 외부 기능 실행을 요청하는 방식',
      simpleMeaning: 'AI가 답을 꾸며내는 대신 검색, 계산, 파일 확인 같은 실제 도구를 호출합니다.',
      category: 'AI Command',
      difficulty: 'intermediate',
      mentalModel: '상담원이 직접 모든 일을 하지 않고 정해진 신청서로 전문 부서에 업무를 요청하는 것과 같습니다.',
      whyItMatters: '모델 내부 지식만으로 불가능한 최신 정보 확인과 외부 상태 변경을 명시적 행동으로 분리합니다.',
      withoutIt: '확인하지 않은 값을 추측하거나 자연어에서 실행 인자를 다시 불안정하게 파싱해야 합니다.',
      mechanism: '도구 이름, 설명, 입력 schema가 context에 주어지고 모델은 호출 필요성을 판단해 구조화된 arguments를 생성합니다.',
      realWorkflow: '도구 설명과 schema를 작게 설계하고 입력을 검증한 뒤 실행 결과를 모델에게 돌려줘 다음 판단에 반영합니다.',
      usagePattern: '검색, 데이터 조회, 계산, 파일 작업, 외부 시스템 행동이 필요한 agent에서 사용합니다.',
      commonPitfall: '모델이 호출을 만들었다고 실행 권한이 자동 승인되는 것은 아닙니다. 부작용과 사용자 승인을 따로 통제해야 합니다.',
      researchBasis: 'OpenAI agent guidance는 model, tools, instructions를 agent의 세 핵심 구성요소로 설명합니다. https://openai.com/business/guides-and-resources/a-practical-guide-to-building-ai-agents/',
      relatedTerms: ['Tool Boundary', 'Schema', 'Agent Loop', 'MCP Tool'],
      promptKo: '필요한 도구 호출만 선택하고 실행 전 인자, 권한, 부작용, 되돌릴 수 있는지를 확인해줘.',
      promptEn: 'Select only the necessary tool call, and verify its arguments, permissions, side effects, and reversibility before execution.',
    }),
    makeFutureTerm({
      deck: 'ai-command',
      term: 'Guardrail',
      pronunciation: '가드레일',
      koreanMeaning: 'AI 입력, 도구 행동, 출력이 정해진 위험 경계를 넘지 않게 검사하는 보호 계층',
      simpleMeaning: '프롬프트의 부탁만 믿지 않고 위험 행동을 별도 규칙과 검사로 막습니다.',
      category: 'Boundary / Safety',
      difficulty: 'intermediate',
      mentalModel: '도로 가장자리 난간처럼 정상 주행을 대신하지는 않지만 큰 이탈이 사고로 이어지는 것을 막습니다.',
      whyItMatters: '확률적인 모델은 지시를 잘 따르더라도 edge case와 공격 입력에서 위험한 행동을 선택할 수 있습니다.',
      withoutIt: '민감정보, prompt injection, 고위험 tool call을 모델의 자기 통제에만 맡기게 됩니다.',
      mechanism: '규칙 기반 검사, 분류기, 입력·출력 validation, tool risk rating을 여러 계층으로 배치해 차단·보류·escalation합니다.',
      realWorkflow: '위험을 식별하고 각 위험에 맞는 독립 검사를 둔 뒤 실제 실패 사례를 eval에 추가해 임계값을 조정합니다.',
      usagePattern: '민감 데이터, 외부 행동, 공개 출력, agent 자동화의 안전 경계를 설계할 때 사용합니다.',
      commonPitfall: '하나의 guardrail로 모든 위험을 막을 수 없으며 인증, 권한, 최소 권한 같은 일반 보안도 함께 필요합니다.',
      researchBasis: 'OpenAI agent guide는 LLM·규칙 기반 guardrail과 tool safeguards를 겹쳐 쓰는 방식을 설명합니다. https://openai.com/business/guides-and-resources/a-practical-guide-to-building-ai-agents/',
      relatedTerms: ['Guard', 'Fail-closed', 'Tool Boundary', 'Prompt Injection'],
      promptKo: '입력, 도구 호출, 출력 단계별 위험과 차단·보류·사람 승인 조건을 guardrail로 설계해줘.',
      promptEn: 'Design layered guardrails for input, tool calls, and output, with explicit block, hold, and human-approval conditions.',
    }),
    makeFutureTerm({
      deck: 'ai-command',
      term: 'Retrieval-Augmented Generation',
      pronunciation: '리트리벌 어그멘티드 제너레이션',
      koreanMeaning: '관련 자료를 검색해 모델 context에 넣은 뒤 답을 생성하는 방식',
      simpleMeaning: '모델의 기억만 믿지 않고 질문과 관련된 문서 조각을 찾아 근거로 제공합니다.',
      category: 'AI Command',
      difficulty: 'advanced',
      mentalModel: '시험 전에 필요한 책의 관련 페이지를 찾아 책상 위에 펼쳐 놓고 답하는 방식입니다.',
      whyItMatters: '최신·사내·도메인 지식을 모델 재학습 없이 공급하고 출처 기반 답변을 만들 수 있습니다.',
      withoutIt: '모델이 모르는 문서 내용을 추측하거나 긴 문서 전체를 매번 context에 넣게 됩니다.',
      mechanism: '질의를 검색 표현으로 바꾸고 후보 문서를 찾은 뒤 관련 조각을 선택·재정렬해 생성 prompt에 넣습니다.',
      realWorkflow: '문서를 chunk로 나누고 metadata와 embedding을 저장합니다. 검색 결과를 rerank하고 답변에 source citation을 붙입니다.',
      usagePattern: '문서 질의응답, 사내 지식 검색, 최신 자료 기반 요약에 사용합니다.',
      commonPitfall: '검색된 자료가 틀리거나 빠지면 생성 모델도 잘못 답할 수 있습니다. 검색 품질과 답변 품질을 따로 평가해야 합니다.',
      researchBasis: 'Lewis et al.은 retrieval과 generation을 결합한 RAG 구조를 제안했습니다. https://arxiv.org/abs/2005.11401',
      relatedTerms: ['Embedding', 'Vector Database', 'Reranker', 'Grounding'],
      promptKo: '먼저 관련 자료를 검색하고 출처별 근거를 분리한 뒤, 검색 결과 안에서만 답하고 누락 가능성을 표시해줘.',
      promptEn: 'Retrieve relevant sources first, separate evidence by source, answer only from the retrieved context, and flag possible retrieval gaps.',
    }),
    makeFutureTerm({
      deck: 'libraries-tools',
      term: 'Embedding',
      pronunciation: '임베딩',
      koreanMeaning: '텍스트·이미지 같은 대상을 의미 관계가 드러나는 숫자 벡터로 표현한 값',
      simpleMeaning: '뜻이 비슷한 항목이 벡터 공간에서 가깝게 놓이도록 만든 좌표입니다.',
      category: 'AI/Data Tools',
      difficulty: 'advanced',
      mentalModel: '문장의 뜻을 여러 의미 축의 좌표로 바꿔 지도 위에 점으로 놓는 것과 같습니다.',
      whyItMatters: '문자열이 정확히 같지 않아도 의미가 비슷한 문서, 이미지, 항목을 찾을 수 있습니다.',
      withoutIt: '키워드가 다르면 같은 의미의 자료를 놓치고 자연어 유사도 검색을 만들기 어렵습니다.',
      mechanism: '모델이 입력을 고정 길이 숫자 배열로 변환하고 cosine similarity 같은 거리 함수로 가까움을 계산합니다.',
      realWorkflow: '같은 embedding model과 전처리로 문서와 질의를 변환하고 metadata filter와 유사도 검색 결과를 평가합니다.',
      usagePattern: 'semantic search, RAG, clustering, recommendation의 후보 검색에 사용합니다.',
      commonPitfall: '가깝다는 것은 사실이 같거나 답이 맞다는 뜻이 아닙니다. model version과 도메인 적합성도 중요합니다.',
      researchBasis: '현대 RAG와 semantic search는 dense vector representation을 검색 신호로 널리 사용합니다. https://arxiv.org/abs/2005.11401',
      relatedTerms: ['Retrieval-Augmented Generation', 'Vector Database', 'Reranker', 'Normalization'],
      promptKo: 'embedding 검색의 model version, 거리 기준, metadata filter, 품질 평가 방법을 분리해 설명해줘.',
    }),
    makeFutureTerm({
      deck: 'libraries-tools',
      term: 'Vector Database',
      pronunciation: '벡터 데이터베이스',
      koreanMeaning: 'embedding 벡터와 metadata를 저장하고 가까운 항목을 검색하는 저장·색인 시스템',
      simpleMeaning: '의미 좌표를 빠르게 비교해 비슷한 문서 후보를 찾습니다.',
      category: 'AI/Data Tools',
      difficulty: 'advanced',
      mentalModel: '수많은 위치 중 현재 좌표와 가까운 장소를 빠르게 찾는 공간 색인 지도와 같습니다.',
      whyItMatters: '대량의 embedding을 전부 순회하지 않고 approximate nearest-neighbor index로 후보를 빠르게 찾습니다.',
      withoutIt: '문서가 많아질수록 유사도 검색 비용과 지연이 커집니다.',
      mechanism: '벡터와 metadata를 index에 넣고 질의 벡터 주변의 근사 이웃을 찾아 score와 함께 반환합니다.',
      realWorkflow: 'chunk ID와 source metadata를 함께 저장하고 filter, top-k, index parameter를 실제 검색 eval로 조정합니다.',
      usagePattern: '대규모 semantic search와 RAG retrieval layer에 사용합니다.',
      commonPitfall: 'vector database가 답을 이해하거나 사실을 검증하는 것은 아닙니다. 후보 검색과 생성·검증을 구분해야 합니다.',
      researchBasis: 'Dense retrieval 시스템은 vector index를 사용해 의미상 가까운 후보를 효율적으로 검색합니다. https://arxiv.org/abs/2004.04906',
      relatedTerms: ['Embedding', 'Reranker', 'Index', 'Retrieval-Augmented Generation'],
      promptKo: 'vector search의 index, top-k, metadata filter, recall과 latency tradeoff를 나눠 검토해줘.',
    }),
    makeFutureTerm({
      deck: 'libraries-tools',
      term: 'Reranker',
      pronunciation: '리랭커',
      koreanMeaning: '1차 검색 후보를 질문과의 관련성 기준으로 다시 정렬하는 모델이나 로직',
      simpleMeaning: '빠른 검색이 모은 후보 중 실제로 답에 도움 되는 순서를 다시 고릅니다.',
      category: 'AI/Data Tools',
      difficulty: 'advanced',
      mentalModel: '도서관 검색이 가져온 책 더미를 전문가가 질문에 가장 맞는 순서로 다시 쌓는 것과 같습니다.',
      whyItMatters: 'embedding 유사도만으로는 단어가 비슷하지만 질문에 답하지 않는 문서가 상위에 올 수 있습니다.',
      withoutIt: '생성 모델의 작은 context에 덜 관련된 조각이 들어가 핵심 근거를 밀어낼 수 있습니다.',
      mechanism: '질의와 각 후보를 함께 읽어 더 정밀한 relevance score를 계산하고 상위 일부만 다음 단계로 넘깁니다.',
      realWorkflow: 'retriever가 넓게 후보를 찾고 reranker가 좁힌 뒤 실제 정답 근거의 recall과 순위를 eval합니다.',
      usagePattern: 'RAG 검색 정확도를 높이고 context packing 전에 후보를 줄일 때 사용합니다.',
      commonPitfall: 'reranker도 비용과 편향이 있으며 1차 검색이 놓친 문서는 되살릴 수 없습니다.',
      researchBasis: '다단계 검색은 빠른 candidate retrieval과 더 정밀한 reranking을 분리해 품질과 비용을 조절합니다. https://arxiv.org/abs/2004.04906',
      relatedTerms: ['Embedding', 'Vector Database', 'Context Packing', 'Recall'],
      promptKo: '1차 검색과 reranking의 책임, 후보 수, 평가 지표, 누락 위험을 분리해서 설명해줘.',
    }),
    makeFutureTerm({
      deck: 'development',
      term: 'Observability',
      pronunciation: '옵저버빌리티',
      koreanMeaning: '외부 출력 신호로 시스템 내부 상태와 실패 원인을 추론할 수 있는 성질',
      simpleMeaning: '로그가 있다는 수준을 넘어 왜 느리고 어디서 틀렸는지 질문에 답할 수 있게 만듭니다.',
      category: 'Runtime / Integration',
      difficulty: 'advanced',
      mentalModel: '닫힌 기계 안을 뜯지 않고 계기판과 센서로 어느 부품이 문제인지 알아내는 능력입니다.',
      whyItMatters: '분산된 앱과 agent는 최종 오류만으로 내부 경로와 최초 실패 지점을 알기 어렵습니다.',
      withoutIt: '재현이 어려운 문제를 추측으로 고치거나 로그 양만 늘리게 됩니다.',
      mechanism: 'logs, metrics, traces를 공통 식별자로 연결해 요청과 상태 변화의 경로, 지연, 오류를 질의할 수 있게 합니다.',
      realWorkflow: '사용자 증상에서 trace를 찾고 느리거나 실패한 span을 좁힌 뒤 관련 log와 metric으로 원인을 확인합니다.',
      usagePattern: 'production debugging, agent trace 분석, 성능과 신뢰성 운영에 사용합니다.',
      commonPitfall: '민감 데이터를 과도하게 수집하거나 목적 없는 로그를 많이 쌓는 것은 observability가 아닙니다.',
      researchBasis: 'OpenAI agent tooling은 trace와 observability를 실행 디버깅과 최적화의 핵심 요소로 설명합니다. https://openai.com/index/new-tools-for-building-agents/',
      relatedTerms: ['Telemetry', 'Execution Trace', 'Trace Span', 'Audit Trail'],
      promptKo: '이 실패를 logs, metrics, traces로 나누고 최초 실패 span과 필요한 상관관계 ID를 정해줘.',
    }),
    makeFutureTerm({
      deck: 'development',
      term: 'Trace Span',
      pronunciation: '트레이스 스팬',
      koreanMeaning: '하나의 trace 안에서 특정 작업 구간의 시작, 종료, 상태, 속성을 기록한 단위',
      simpleMeaning: '전체 실행 경로를 도구 호출이나 함수 처리 같은 작은 시간 구간으로 나눕니다.',
      category: 'Runtime / Integration',
      difficulty: 'advanced',
      mentalModel: '긴 이동 경로를 출발, 환승, 도착 구간별 표로 나눈 것과 같습니다.',
      whyItMatters: '어느 단계가 느렸고 어디서 오류가 시작됐는지 전체 trace 안에서 정확히 찾습니다.',
      withoutIt: '하나의 큰 실행 시간만 보여 내부 병목과 실패 전파를 구분하기 어렵습니다.',
      mechanism: '각 작업이 start/end time, status, attributes, parent-child 관계를 기록해 trace tree를 만듭니다.',
      realWorkflow: 'root span에서 실패 경로를 따라가 child span의 duration, error, input metadata를 비교합니다.',
      usagePattern: '분산 요청, agent tool call, 데이터 pipeline 성능 분석에 사용합니다.',
      commonPitfall: 'span 이름과 attribute 기준이 일관되지 않거나 민감한 payload를 기록하면 분석과 보안이 모두 나빠집니다.',
      researchBasis: 'Tracing 시스템은 실행을 parent-child span으로 표현해 경로와 지연을 분석합니다. https://opentelemetry.io/docs/concepts/signals/traces/',
      relatedTerms: ['Observability', 'Execution Trace', 'Telemetry', 'Latency'],
      promptKo: '실행을 parent-child span으로 나누고 각 구간의 입력 요약, 상태, 지연, 오류를 기록해줘.',
    }),
    makeFutureTerm({
      deck: 'ai-command',
      term: 'Prompt Caching',
      pronunciation: '프롬프트 캐싱',
      koreanMeaning: '반복되는 프롬프트 앞부분의 처리 결과를 재사용해 지연과 비용을 줄이는 방식',
      simpleMeaning: '매번 같은 긴 지시와 도구 정의를 처음부터 다시 처리하지 않게 합니다.',
      category: 'Prompt Quality',
      difficulty: 'advanced',
      mentalModel: '같은 책의 공통 앞부분은 미리 읽어 두고 매 요청에서 달라진 뒷부분만 새로 읽는 것과 같습니다.',
      whyItMatters: '장기 지시, 많은 tool schema, 공통 reference가 있는 요청의 반복 비용을 줄일 수 있습니다.',
      withoutIt: '변하지 않는 긴 prefix를 요청마다 다시 처리해 latency와 token 비용이 커집니다.',
      mechanism: 'provider가 동일한 prompt prefix를 식별해 내부 계산을 재사용하고 달라진 suffix만 추가 처리합니다.',
      realWorkflow: '안정적인 system instruction과 tool definition을 앞에 두고 요청별 동적 정보는 뒤에 배치하며 cache hit를 측정합니다.',
      usagePattern: '동일 agent 설정으로 많은 요청을 처리하거나 긴 reference context를 반복 사용할 때 고려합니다.',
      commonPitfall: '문자 하나나 tool 순서가 바뀌어도 cache hit가 깨질 수 있고, cache가 답 자체를 저장하는 것은 아닙니다.',
      researchBasis: 'OpenAI Prompt Caching 문서는 반복 prefix 처리 재사용으로 latency와 비용을 줄이는 방식을 설명합니다. https://developers.openai.com/api/docs/guides/prompt-caching',
      relatedTerms: ['Context Packing', 'Context Window', 'Cache', 'Tool Calling'],
      promptKo: '고정 prompt prefix와 요청별 동적 context를 분리하고 cache hit를 깨뜨리는 변동 요소를 찾아줘.',
      promptEn: 'Separate the stable prompt prefix from request-specific context and identify changes that would prevent prompt-cache reuse.',
    }),
    makeFutureTerm({
      deck: 'ai-command',
      term: 'Computer Use',
      pronunciation: '컴퓨터 유즈',
      koreanMeaning: 'AI가 화면을 보고 마우스·키보드 행동으로 사용자 인터페이스를 조작하는 능력',
      simpleMeaning: 'API가 없는 앱도 사람이 하듯 화면을 통해 조작하게 합니다.',
      category: 'AI Command',
      difficulty: 'advanced',
      mentalModel: '원격 작업자가 화면을 보며 클릭하고 입력하지만 매 단계의 화면 상태를 다시 확인해야 하는 것과 같습니다.',
      whyItMatters: '표준 API나 tool integration이 없는 레거시·GUI 작업을 자동화할 수 있습니다.',
      withoutIt: '화면 전용 업무는 사람이 직접 하거나 별도 automation 코드를 만들어야 합니다.',
      mechanism: '모델이 screenshot과 접근성 정보를 해석해 다음 pointer·keyboard action을 선택하고 새 화면을 관찰합니다.',
      realWorkflow: '허용 앱과 목표를 제한하고 읽기 단계부터 시작합니다. 제출·삭제·결제 같은 고위험 행동 전에는 사람이 승인합니다.',
      usagePattern: '브라우저·데스크톱 앱 테스트와 API 없는 반복 작업에 사용합니다.',
      commonPitfall: '화면 변화, 잘못된 포커스, 숨은 상태 때문에 오조작할 수 있으므로 작은 행동과 화면 재확인이 필요합니다.',
      researchBasis: 'OpenAI는 agent built-in tool의 하나로 computer use를 소개하고 외부 UI 상호작용에 사용한다고 설명합니다. https://openai.com/index/new-tools-for-building-agents/',
      relatedTerms: ['Agent Loop', 'Tool Boundary', 'Guardrail', 'Human-in-the-loop'],
      promptKo: '한 번에 한 UI 행동만 수행하고 화면 변화를 확인한 뒤, 되돌릴 수 없는 행동 전에는 사용자 승인을 요청해줘.',
      promptEn: 'Perform one UI action at a time, verify the resulting screen, and request approval before any irreversible action.',
    }),
    makeFutureTerm({
      deck: 'ai-command',
      term: 'Model Routing',
      pronunciation: '모델 라우팅',
      koreanMeaning: '작업의 난이도, 위험, 속도, 비용에 맞춰 사용할 모델을 선택하는 방식',
      simpleMeaning: '모든 요청을 가장 큰 모델에 보내지 않고 일의 성격에 맞는 처리 경로를 고릅니다.',
      category: 'AI Command',
      difficulty: 'advanced',
      mentalModel: '간단한 문의와 전문 수술을 같은 담당자에게 보내지 않고 난이도에 맞는 창구로 배정하는 것과 같습니다.',
      whyItMatters: '품질, latency, cost의 균형을 잡고 고위험 문제에 더 강한 추론 능력을 집중할 수 있습니다.',
      withoutIt: '단순 작업에 과도한 비용을 쓰거나 복잡한 작업을 약한 모델에 보내 실패율이 높아질 수 있습니다.',
      mechanism: '입력 특성과 위험 신호를 분류해 model, reasoning effort, tool access, human review 경로를 선택합니다.',
      realWorkflow: '대표 작업별 eval을 만들고 최소 요구 성능을 만족하는 경로를 정한 뒤 실패·불확실성에서 상위 모델로 escalation합니다.',
      usagePattern: '대량 AI 기능, agent orchestration, 비용·속도 최적화에 사용합니다.',
      commonPitfall: '정확한 eval 없이 가격만 보고 routing하면 어려운 사례가 조용히 낮은 품질 경로로 갈 수 있습니다.',
      researchBasis: 'OpenAI agent guide는 단순 작업과 복잡한 작업에 모델 선택 전략을 달리하고 eval로 기준선을 세울 것을 권합니다. https://openai.com/business/guides-and-resources/a-practical-guide-to-building-ai-agents/',
      relatedTerms: ['Evals', 'Escalation Criteria', 'Tradeoff', 'Capability Matrix'],
      promptKo: '이 작업의 난이도, 위험, latency, 비용 기준으로 model routing 규칙과 escalation 조건을 정해줘.',
      promptEn: 'Define model-routing rules and escalation conditions based on task difficulty, risk, latency, and cost.',
    }),
    makeFutureTerm({
      deck: 'ai-command',
      term: 'Multimodal Input',
      pronunciation: '멀티모달 인풋',
      koreanMeaning: '텍스트와 이미지·음성·영상 같은 여러 형태의 정보를 함께 제공하는 입력',
      simpleMeaning: '글 설명만이 아니라 화면, 사진, 문서 이미지 같은 실제 시각 자료도 함께 판단하게 합니다.',
      category: 'AI Command',
      difficulty: 'intermediate',
      mentalModel: '설명만 듣는 대신 문서와 사진을 같이 펼쳐 놓고 같은 대상을 여러 감각으로 확인하는 것과 같습니다.',
      whyItMatters: '레이아웃, 차트, UI 상태, 손상된 문서처럼 텍스트 추출만으로 사라지는 정보를 사용할 수 있습니다.',
      withoutIt: '사용자가 화면을 부정확하게 설명하거나 OCR이 놓친 공간 관계를 모델이 알 수 없습니다.',
      mechanism: '각 modality가 모델이 처리할 representation으로 변환되고 text instruction과 함께 attention에서 관계를 형성합니다.',
      realWorkflow: '원본 품질을 유지해 자료를 제공하고 무엇을 볼지 지시한 뒤 시각 관찰, 해석, 확인 불가를 분리합니다.',
      usagePattern: 'UI 검토, 스크린샷 오류 분석, 차트·문서 이미지 해석에 사용합니다.',
      commonPitfall: '이미지를 봤다는 사실이 작은 글자와 가려진 부분까지 정확히 읽었다는 뜻은 아닙니다. 확대와 원본 확인이 필요합니다.',
      researchBasis: '최신 AI 시스템은 text뿐 아니라 image 등 여러 modality를 입력으로 처리하는 workflow를 지원합니다.',
      relatedTerms: ['OCR confidence', 'Grounding', 'Computer Use', 'Context Window'],
      promptKo: '이미지에서 직접 관찰한 사실, 그 사실의 해석, 읽을 수 없는 부분을 분리해서 답해줘.',
      promptEn: 'Separate directly observed visual facts, interpretations, and unreadable or uncertain regions.',
    }),
    makeFutureTerm({
      deck: 'development',
      term: 'SWE-bench',
      pronunciation: '에스더블유이 벤치',
      koreanMeaning: '실제 GitHub 이슈와 저장소 테스트로 코딩 agent의 문제 해결 능력을 평가하는 벤치마크',
      simpleMeaning: 'agent가 실제 프로젝트의 버그를 고치고 테스트를 통과하는지 측정합니다.',
      category: 'Review / QA',
      difficulty: 'advanced',
      mentalModel: '알고리즘 퀴즈가 아니라 실제 정비소에서 고장 난 차를 주고 수리 결과를 검사하는 시험과 같습니다.',
      whyItMatters: '코드 생성 문장만이 아니라 저장소 탐색, 수정, 실행 검증을 포함한 agent 능력을 비교합니다.',
      withoutIt: '짧은 코드 문제 성능을 실제 software engineering 능력으로 과대해석할 수 있습니다.',
      mechanism: '고정된 repository snapshot과 issue를 주고 agent patch를 적용한 뒤 기존·추가 테스트로 해결 여부를 판정합니다.',
      realWorkflow: 'task version, 실행 환경, 통과 테스트 범위를 확인하고 contamination과 harness 차이를 함께 해석합니다.',
      usagePattern: '코딩 agent 모델·하네스 성능 발표와 평가 논문을 읽을 때 사용합니다.',
      commonPitfall: '하나의 benchmark 점수는 실제 사용자 질의, 언어, 저장소 규모, 긴 작업 능력을 모두 대표하지 않습니다.',
      researchBasis: 'SWE-bench는 실제 GitHub issue 해결을 repository test로 판정하는 benchmark를 제안했습니다. https://arxiv.org/abs/2310.06770',
      relatedTerms: ['Execution-based Evaluation', 'Benchmark Contamination', 'Harness Engineering', 'Regression'],
      promptKo: 'SWE-bench 점수를 모델, harness, 실행 환경, 오염 가능성, 실제 업무 대표성으로 나눠 해석해줘.',
    }),
    makeFutureTerm({
      deck: 'development',
      term: 'Recall',
      pronunciation: '리콜',
      koreanMeaning: '실제로 찾아야 할 전체 항목 중 시스템이 찾아낸 비율',
      simpleMeaning: '중요한 자료를 얼마나 빠뜨리지 않고 찾았는지 보는 지표입니다.',
      category: 'Review / QA',
      difficulty: 'intermediate',
      mentalModel: '창고에 있는 불량품 전체 중 검사기가 몇 개를 놓치지 않고 잡았는지 세는 것과 같습니다.',
      whyItMatters: 'RAG, 검색, 분류, 테스트에서 중요한 항목을 놓치는 위험을 수치로 봅니다.',
      withoutIt: '검색 결과 몇 개가 좋아 보여도 실제 관련 자료를 대부분 놓쳤는지 알 수 없습니다.',
      mechanism: 'true positive를 true positive와 false negative의 합으로 나눠 계산합니다.',
      realWorkflow: '사람이 관련 항목을 표시한 평가 세트를 만들고 검색 top-k 안에 포함된 비율을 query별로 측정합니다.',
      usagePattern: 'RAG retrieval, 증거 검색, 이상 탐지, test coverage의 누락 위험을 비교할 때 사용합니다.',
      commonPitfall: '후보를 많이 반환하면 recall은 높아져도 쓸모없는 결과가 늘 수 있으므로 precision과 함께 봐야 합니다.',
      researchBasis: '정보 검색은 precision과 recall을 함께 사용해 관련 결과의 정확성과 누락을 측정합니다.',
      relatedTerms: ['Precision', 'Reranker', 'Test Coverage', 'Relevance'],
      promptKo: '이 검색의 recall을 평가할 정답 세트, top-k, 누락 사례, precision tradeoff를 정해줘.',
    }),
    makeFutureTerm({
      deck: 'development',
      term: 'Precision',
      pronunciation: '프리시전',
      koreanMeaning: '시스템이 찾아냈다고 한 항목 중 실제로 맞는 항목의 비율',
      simpleMeaning: '검색 결과에 쓸모없는 오답이 얼마나 적은지 보는 지표입니다.',
      category: 'Review / QA',
      difficulty: 'intermediate',
      mentalModel: '검사기가 불량이라고 울린 제품 중 실제 불량품이 얼마나 되는지 세는 것과 같습니다.',
      whyItMatters: '잘못된 후보가 많으면 사람 검토 비용과 AI context 잡음이 커집니다.',
      withoutIt: '많이 찾았다는 이유만으로 검색 품질이 좋다고 오해할 수 있습니다.',
      mechanism: 'true positive를 true positive와 false positive의 합으로 나눠 계산합니다.',
      realWorkflow: '반환된 결과를 사람 또는 정답 label과 비교해 query별 precision과 오류 유형을 기록합니다.',
      usagePattern: '검색, 분류, 경보, 자동 검토가 잘못된 후보를 얼마나 만드는지 볼 때 사용합니다.',
      commonPitfall: '아주 적은 후보만 반환하면 precision은 높아도 중요한 항목을 놓칠 수 있으므로 recall과 함께 봐야 합니다.',
      researchBasis: '정보 검색은 precision과 recall의 균형으로 관련 결과와 누락을 함께 평가합니다.',
      relatedTerms: ['Recall', 'Reranker', 'Finding', 'Relevance'],
      promptKo: '이 검색의 precision을 평가할 정답 기준, 오탐 유형, recall tradeoff를 정해줘.',
    }),
    makeFutureTerm({
      deck: 'development',
      term: 'Latency',
      pronunciation: '레이턴시',
      koreanMeaning: '하나의 요청이 시작된 뒤 응답이나 작업 완료까지 걸린 시간',
      simpleMeaning: '사용자 한 명이 결과를 기다리는 시간을 나타냅니다.',
      category: 'Runtime / Integration',
      difficulty: 'intermediate',
      mentalModel: '주문 한 건을 넣고 음식이 나올 때까지 개인이 기다린 시간과 같습니다.',
      whyItMatters: 'agent와 앱이 정확해도 응답이 지나치게 느리면 실제 사용성과 비용이 나빠집니다.',
      withoutIt: '평균 처리량만 보고 일부 사용자가 매우 오래 기다리는 tail latency를 놓칠 수 있습니다.',
      mechanism: 'queue wait, network, model inference, tool execution, rendering 같은 구간 시간이 합쳐져 end-to-end latency가 됩니다.',
      realWorkflow: '전체 시간을 trace span으로 나누고 p50, p95, p99를 비교해 느린 구간과 긴 꼬리를 찾습니다.',
      usagePattern: 'API, UI, agent tool loop, 데이터 처리의 응답성을 분석할 때 사용합니다.',
      commonPitfall: '평균값 하나는 드문 장시간 지연을 숨길 수 있으며 throughput과 같은 지표가 아닙니다.',
      researchBasis: '분산 시스템과 observability에서는 latency distribution과 percentile로 사용자 대기 시간을 분석합니다.',
      relatedTerms: ['Throughput', 'Trace Span', 'Performance', 'Queue'],
      promptKo: '전체 latency를 queue, network, model, tool, render span으로 나누고 p95 병목을 찾아줘.',
    }),
    makeFutureTerm({
      deck: 'development',
      term: 'Throughput',
      pronunciation: '스루풋',
      koreanMeaning: '일정 시간 동안 시스템이 처리한 작업량',
      simpleMeaning: '한 명의 대기 시간이 아니라 시스템 전체가 얼마나 많은 일을 끝내는지 봅니다.',
      category: 'Runtime / Integration',
      difficulty: 'intermediate',
      mentalModel: '주문 한 건의 대기 시간이 아니라 주방이 한 시간에 몇 접시를 내는지 보는 값입니다.',
      whyItMatters: '동시 사용자가 늘 때 시스템이 감당할 수 있는 처리 능력과 비용을 판단합니다.',
      withoutIt: '개별 요청은 빨라도 전체 부하에서 queue가 쌓이고 시스템이 포화되는 시점을 놓칩니다.',
      mechanism: '완료된 요청 수나 처리 데이터량을 시간으로 나누며 concurrency, resource, batching의 영향을 받습니다.',
      realWorkflow: '부하를 단계적으로 높여 throughput, latency, error rate가 함께 변하는 포화점을 찾습니다.',
      usagePattern: '서버, pipeline, agent fleet, batch processing의 용량을 계획할 때 사용합니다.',
      commonPitfall: 'throughput을 높이기 위해 batching이나 concurrency를 늘리면 개별 latency와 오류가 악화될 수 있습니다.',
      researchBasis: '시스템 성능은 throughput과 latency를 함께 측정해 용량과 사용자 대기 시간의 tradeoff를 봅니다.',
      relatedTerms: ['Latency', 'Queue', 'Rate Limit', 'Performance'],
      promptKo: '부하별 throughput, p95 latency, error rate를 함께 비교해 포화점을 찾아줘.',
    }),
  ]
}

function makeMcpTerms(): RawDevTerm[] {
  const common = {
    deck: 'libraries-tools' as const,
    category: 'AI Protocols',
    researchBasis: `MCP 공식 아키텍처는 host-client-server 구조와 tools, resources, prompts 역할을 정의합니다. ${mcpArchitectureSource}`,
  }

  return [
    makeFutureTerm({
      ...common,
      term: 'Model Context Protocol',
      pronunciation: '모델 컨텍스트 프로토콜',
      koreanMeaning: 'AI 애플리케이션과 외부 도구·데이터를 표준 방식으로 연결하는 개방형 프로토콜',
      simpleMeaning: '각 서비스마다 제각각 연결 코드를 만들지 않고 공통 메시지 규칙으로 능력을 노출합니다.',
      difficulty: 'intermediate',
      mentalModel: '여러 전자기기가 같은 규격의 포트와 통신 규칙으로 연결되는 것과 같습니다.',
      whyItMatters: 'AI host가 다양한 도구와 자료를 일관되게 발견하고 권한 경계 안에서 사용할 수 있습니다.',
      withoutIt: '연동마다 별도 adapter와 문서가 필요하고 도구 의미와 권한 표현이 쉽게 달라집니다.',
      mechanism: 'host 안의 client가 JSON-RPC session을 통해 server가 제공하는 tools, resources, prompts를 협상하고 호출합니다.',
      realWorkflow: 'host가 server에 연결하고 capability를 협상한 뒤 목록을 조회합니다. 사용자 승인과 경계에 따라 필요한 기능만 호출합니다.',
      usagePattern: 'Codex·AI 앱이 로컬 또는 원격 데이터와 도구를 표준 방식으로 사용할 때 등장합니다.',
      commonPitfall: 'MCP가 자동으로 안전성을 보장하는 것은 아닙니다. server 신뢰, tool 권한, 사용자 동의를 별도로 관리해야 합니다.',
      relatedTerms: ['MCP Host', 'MCP Client', 'MCP Server', 'JSON-RPC'],
      promptKo: 'MCP 연결을 host, client, server, tool, resource, prompt 역할로 나눠 설명해줘.',
    }),
    makeMcpRole('MCP Host', '엠씨피 호스트', 'MCP 연결과 사용자 경험·권한 정책을 소유하는 AI 애플리케이션', '여러 client를 관리하며 어떤 server와 정보를 모델에게 보여줄지 결정합니다.', '호텔 프런트처럼 외부 서비스와 사용자를 연결하면서 최종 접근 규칙을 관리합니다.', 'host가 server별 client를 만들고 사용자 승인, context 조합, 모델 호출을 조정합니다.', ['MCP Client', 'MCP Server', 'Capability State']),
    makeMcpRole('MCP Client', '엠씨피 클라이언트', '하나의 MCP server와 연결된 통신 세션 구성요소', 'host 내부에서 server 한 곳과 메시지를 주고받고 capability를 협상합니다.', '한 업체와 전용으로 연락하는 창구처럼 server마다 별도 연결을 유지합니다.', 'client가 초기화 요청으로 protocol version과 capability를 맞춘 뒤 목록 조회와 호출을 전달합니다.', ['MCP Host', 'MCP Server', 'JSON-RPC']),
    makeMcpRole('MCP Server', '엠씨피 서버', 'AI가 사용할 tool, resource, prompt를 MCP 규칙으로 제공하는 프로그램', '외부 시스템의 능력과 데이터를 표준 설명과 호출 방식으로 노출합니다.', '창고 안의 물건을 직접 흩뿌리지 않고 목록과 출고 창구를 제공하는 역할입니다.', 'server는 지원 capability를 선언하고 요청에 따라 목록과 결과를 반환하며 접근 가능한 범위를 자체적으로 지켜야 합니다.', ['MCP Client', 'MCP Tool', 'MCP Resource']),
    makeMcpRole('MCP Tool', '엠씨피 툴', '모델이 판단에 따라 호출할 수 있는 실행 가능한 기능', '검색, 계산, 파일 쓰기처럼 외부 상태를 읽거나 바꿀 수 있는 행동입니다.', '버튼을 누르면 실제 기계가 움직이는 조작부와 같습니다.', 'tool은 이름, 설명, 입력 schema를 제공하고 호출 결과를 content 또는 structured content로 반환합니다.', ['Tool Boundary', 'Schema', 'Side Effect']),
    makeMcpRole('MCP Resource', '엠씨피 리소스', '사용자나 애플리케이션이 context로 선택해 제공할 수 있는 데이터', '파일, 문서, schema처럼 읽을 자료를 URI와 metadata로 노출합니다.', '도서관 서가처럼 읽을 자료의 위치와 설명을 제공하지만 행동을 실행하지는 않습니다.', 'client가 resource 목록이나 template을 조회하고 필요한 URI를 읽어 모델 context에 포함합니다.', ['Context Engineering', 'Provenance', 'MCP Tool']),
    makeMcpRole('MCP Prompt', '엠씨피 프롬프트', 'server가 제공하는 재사용 가능한 상호작용 템플릿', '특정 작업을 수행하는 메시지 구조와 필요한 인자를 미리 정의합니다.', '자주 쓰는 업무 양식을 꺼내 필요한 빈칸만 채우는 것과 같습니다.', '사용자가 prompt를 선택하고 인자를 주면 server가 model에 보낼 messages를 구성해 반환합니다.', ['Prompt', 'Few-shot Prompting', 'MCP Resource']),
    makeMcpRole('MCP Roots', '엠씨피 루츠', 'client가 server에게 집중할 파일 시스템 경계를 알려주는 기능', 'server가 어느 디렉터리를 작업 범위로 봐야 하는지 좌표를 제공합니다.', '작업 지도에서 허용된 구역만 선으로 표시해 주는 것과 같습니다.', 'client가 root URI 목록과 변경 알림을 제공하고 server는 그 범위를 기준으로 상대 경로와 검색을 구성합니다.', ['Boundary', 'Scope', 'Least Privilege'], mcpClientSource),
    makeMcpRole('MCP Elicitation', '엠씨피 일리시테이션', 'server가 작업 중 필요한 추가 정보를 사용자에게 구조적으로 요청하는 기능', '빈 정보를 추측하지 않고 host를 통해 사용자에게 확인 질문을 보냅니다.', '담당자가 서류의 빈칸을 임의로 채우지 않고 본인 확인을 요청하는 절차와 같습니다.', 'server가 schema와 설명을 보내면 host가 사용자에게 표시하고 승인·거절·취소 결과를 돌려줍니다.', ['Clarifying Question', 'Human-in-the-loop', 'MCP Host'], mcpClientSource),
    makeMcpRole('MCP Sampling', '엠씨피 샘플링', 'server가 host의 모델 호출 능력을 요청하는 MCP 기능', 'server가 자체 모델 키 없이도 client 통제 아래 LLM 작업을 요청할 수 있습니다.', '외부 부서가 중앙 분석실에 판단을 의뢰하되 최종 승인권은 중앙에 남는 구조입니다.', 'server가 messages와 model preferences를 보내고 host가 사용자 승인과 정책을 적용해 모델 결과를 반환합니다.', ['MCP Host', 'Tool Boundary', 'Human-in-the-loop'], mcpClientSource),
    makeMcpRole('JSON-RPC', '제이슨 알피씨', 'JSON 메시지로 원격 메서드 호출과 결과·오류를 표현하는 프로토콜', '요청 ID, 메서드, 인자, 결과를 정해진 JSON 모양으로 주고받습니다.', '봉투에 수신자, 업무명, 서류, 회신 번호를 정해 보내는 통신 양식과 같습니다.', 'client가 id가 있는 request를 보내고 server가 같은 id의 result 또는 error로 응답하며 notification은 응답 없이 전달됩니다.', ['Model Context Protocol', 'Schema', 'Contract']),
  ]
}

function makeMcpRole(
  term: string,
  pronunciation: string,
  koreanMeaning: string,
  simpleMeaning: string,
  mentalModel: string,
  mechanism: string,
  relatedTerms: string[],
  researchBasis = mcpArchitectureSource,
) {
  return makeFutureTerm({
    deck: 'libraries-tools',
    term,
    pronunciation,
    koreanMeaning,
    simpleMeaning,
    category: 'AI Protocols',
    difficulty: 'advanced',
    mentalModel,
    whyItMatters: '역할을 정확히 구분해야 데이터 제공, 실제 행동, 사용자 승인, 통신 책임을 서로 혼동하지 않습니다.',
    withoutIt: '모든 연결 요소를 “MCP”라고만 부르면 누가 권한을 가지고 무엇이 실제 행동을 하는지 판단하기 어렵습니다.',
    mechanism,
    realWorkflow: '초기 연결과 capability 협상 후 필요한 목록을 조회하고, 승인된 범위에서 요청·응답을 기록하며 오류를 처리합니다.',
    usagePattern: 'MCP 설정, 보안 검토, tool/resource 설계, 연결 오류를 설명할 때 사용합니다.',
    commonPitfall: '프로토콜 기능이 존재한다는 것과 현재 host가 그 기능을 지원·허용한다는 것은 별개입니다.',
    researchBasis: researchBasis.startsWith('http') ? `MCP 공식 문서에 정의된 역할입니다. ${researchBasis}` : researchBasis,
    relatedTerms,
    promptKo: `${term}의 소유 주체, 입력, 출력, 권한 경계, 실패 지점을 나눠 설명해줘.`,
  })
}

function makeFutureTerm(seed: FutureTermSeed): RawDevTerm {
  const domainLabel = getDomainLabel(seed.deck)
  const goodExpression = seed.promptEn ? `${seed.promptKo}\nEN: ${seed.promptEn}` : seed.promptKo

  return {
    id: `future-${seed.deck}-${slugify(seed.term)}`,
    deck: seed.deck,
    domainLabel,
    term: seed.term,
    pronunciation: seed.pronunciation,
    koreanMeaning: seed.koreanMeaning,
    simpleMeaning: seed.simpleMeaning,
    category: seed.category,
    difficulty: seed.difficulty,
    joovisUsage:
      seed.deck === 'dispute-integration'
        ? undefined
        : `${seed.term}을 실제 AI·개발 작업의 흐름과 검증 기준을 설명하는 데 사용합니다.`,
    disputeUsage:
      seed.deck === 'dispute-integration'
        ? `${seed.term}을 일반적인 증거·문서 검토 절차를 설명하는 데 사용합니다.`
        : undefined,
    checkQuestion: `${seed.term}은 어떤 입력을 받아 어떤 과정을 거치며, 실패를 무엇으로 확인하나요?`,
    badExpression: seed.deck === 'ai-command' ? 'AI가 알아서 가장 좋은 방식으로 해줘.' : undefined,
    goodExpression: seed.deck === 'ai-command' ? goodExpression : undefined,
    gptPromptExample: seed.promptEn ?? seed.promptKo,
    codexPromptExample: seed.promptKo,
    mentalModel: seed.mentalModel,
    whyItMatters: seed.whyItMatters,
    withoutIt: seed.withoutIt,
    mechanism: seed.mechanism,
    realWorkflow: seed.realWorkflow,
    usagePattern: seed.usagePattern,
    commonPitfall: seed.commonPitfall,
    expertNote: '용어 이름보다 입력, 상태 변화, 실패 조건, 검증 방법을 함께 설명할 수 있어야 실제로 이해한 것입니다.',
    researchBasis: seed.researchBasis,
    relatedTerms: seed.relatedTerms,
  }
}

function getDomainLabel(deck: DeckId) {
  if (deck === 'ai-command') return 'AI 지휘'
  if (deck === 'development') return '개발 기본'
  if (deck === 'libraries-tools') return '라이브러리/도구'
  if (deck === 'joovis-architecture') return 'JOOVIS'
  return '분쟁통합'
}

function slugify(term: string) {
  const slug = term
    .normalize('NFKD')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
  return slug || term.normalize('NFKC').replace(/[^\p{L}\p{N}]+/gu, '')
}
