import type { DeckId, LearningPriority, RawDevTerm } from './types'

type CuratableTerm = Pick<
  RawDevTerm,
  'deck' | 'term' | 'category' | 'difficulty' | 'learningPriority' | 'selectionReason'
>

const coreTerms: Record<DeckId, ReadonlySet<string>> = {
  'ai-command': termSet([
    'Context',
    'Capability State',
    'Prompt',
    'Instruction',
    'System Instruction',
    'User Intent',
    'Assumption',
    'Clarifying Question',
    'Plan',
    'Task Boundary Prompt',
    'Output Contract',
    'Evidence Request',
    'Stop Condition',
    'Review Lens',
    'Context Compression',
    'Verification Prompt',
    'Intent Framing',
    'Constraint Stack',
    'Rubric',
    'Grounding',
    'Evidence Ladder',
    'Decision Record',
    'Counterexample',
    'Acceptance Probe',
    'Failure Mode',
    'Escalation Criteria',
    'Instruction Priority',
    'Prompt Injection',
    'Tool Boundary',
    'Confidence',
    'Tradeoff',
    'Define the output contract',
    'Separate facts from inference',
    'Ask clarifying questions first',
    'Inspect before editing',
    'Do not modify files yet',
    'Stop on boundary uncertainty',
    'Use a minimal patch',
    'Verify against source of truth',
    'List risks before implementation',
    'Explain as a workflow',
    'Give Korean explanation and English command',
    'Review only actionable findings',
    'Show the decision tradeoff',
    'Preserve user changes',
    'Return a concise final report',
    'Reference Text Grounding',
    'Delimiter Framing',
    'Few-shot Prompting',
    'Tool-Augmented Prompting',
    'Verifier Pass',
    'Rubric-first Evaluation',
    'Prompt Regression Test',
    'Adversarial Check',
    'Answer Calibration',
    'Context Packing',
    'Structured Output Prompting',
    'Context Engineering',
    'Context Window',
    'Lost in the Middle',
    'Agent Loop',
    'Harness Engineering',
    'Eval-driven Development',
    'Execution Trace',
    'Long-Horizon Task',
    'Evals',
    'Tool Calling',
    'Guardrail',
    'Retrieval-Augmented Generation',
    'Prompt Caching',
    'Computer Use',
    'Model Routing',
    'Multimodal Input',
  ]),
  development: termSet([
    'Scope',
    'Boundary',
    'Source of Truth',
    'Contract',
    'Interface',
    'Schema',
    'Artifact',
    'Provenance',
    'Diff',
    'Runtime',
    'Static',
    'Guard',
    'Checker',
    'Smoke Test',
    'Regression',
    'Acceptance Criteria',
    'Handoff',
    'Telemetry',
    'Upstream',
    'Downstream',
    'Dependency',
    'Coupling',
    'Decoupling',
    'Adapter',
    'Port',
    'Pipeline',
    'Orchestration',
    'Fixture',
    'Mock',
    'Stub',
    'Sandbox',
    'Dry Run',
    'Idempotent',
    'Side Effect',
    'Invariant',
    'Fail-closed',
    'Rollback',
    'Migration',
    'Constraint',
    'Checklist',
    'State',
    'Validation',
    'Normalization',
    'Serialization',
    'Versioning',
    'Backward Compatibility',
    'Fallback',
    'Timeout',
    'Retry',
    'Cache',
    'Offline-first',
    'Least Privilege',
    'Redaction',
    'Secret',
    'Audit Trail',
    'Read-only Mode',
    'Edge Case',
    'Happy Path',
    'Repro Steps',
    'Finding',
    'Severity',
    'Test Coverage',
    'Typecheck',
    'Lint',
    'Build',
    'Commit',
    'Branch',
    'Pull Request',
    'Merge Conflict',
    'Feature Flag',
    'LocalStorage',
    'Service Worker',
    'Manifest',
    'Installability',
    'Control Flow',
    'State Machine',
    'Transition',
    'Transaction',
    'Parser',
    'Type Inference',
    'Type Narrowing',
    'Concurrency',
    'Race Condition',
    'Cache Invalidation',
    'Retry Policy',
    'Backoff',
    'Circuit Breaker',
    'Idempotency Key',
    'Event Loop',
    'Memory Leak',
    'Change Control',
    'Deterministic Verification',
    'Worktree Isolation',
    'Feedback Loop',
    'Observability',
  ]),
  'libraries-tools': termSet([
    'React',
    'Component',
    'Hook',
    'Vite',
    'TypeScript',
    'Node.js',
    'npm',
    'package.json',
    'ESLint',
    'Python',
    'pandas',
    'DuckDB',
    'JSON',
    'Parquet',
    'CLI',
    'PowerShell',
    'GitHub',
    'Vercel',
    'Cloudflare Pages',
    'Service Worker API',
    'JSX',
    'Props',
    'State',
    'Context Provider',
    'Reducer',
    'Memoization',
    'Reconciliation',
    'Bundle',
    'Transpilation',
    'Tree Shaking',
    'Source Map',
    'Hot Module Replacement',
    'Lockfile',
    'Semantic Versioning',
    'DataFrame',
    'SQL Query',
    'Browser DevTools',
    'Lighthouse',
    'Playwright',
    'Vitest',
    'Accessibility',
    'Breaking Change',
    'Debugging',
    'Dev Server',
    'Module',
    'Network Tab',
    'Stack Trace',
    'Unit Test',
    'Virtual DOM',
    'Model Context Protocol',
    'MCP Host',
    'MCP Client',
    'MCP Server',
    'MCP Tool',
    'MCP Resource',
    'MCP Prompt',
    'JSON-RPC',
    'Embedding',
    'Vector Database',
    'Reranker',
  ]),
  'joovis-architecture': termSet([
    'LOCK',
    'WBS',
    'Relay',
    'Current Truth',
    'Data Block',
    'Dynamic Knowledge Surface',
    'Agent Foundry',
    'Replay',
    'Autopsy',
    'Boundary Ledger',
    'Truth Packet',
    'Command Surface',
    'Review Cockpit',
    'State Capsule',
    'Handoff Packet',
    'Control Plane',
    'Data Plane',
    'Truth Graph',
    'State Ledger',
    'Replay Harness',
    'Autopsy Trail',
    'Capability Matrix',
    'Risk Gate',
    'Review Gate',
    'Snapshot',
    'Checkpoint',
    'Golden Path',
    'Degraded Mode',
    'Operator Loop',
    'Human-in-the-loop',
    'Knowledge Boundary',
    'Immutable Log',
    'Drift Monitor',
  ]),
  'dispute-integration': termSet([
    '원본대조',
    '직접인용',
    '간접인용',
    '요약오염',
    '증거목록',
    '쟁점',
    '주장',
    '반박',
    '입증',
    '소명',
    '타임라인',
    '기관별 판단',
    '판단 괴리',
    '출처추적',
    '인용안전등급',
    '민감정보',
    '비식별화',
    'append-only',
    'verification queue',
    'evidence item',
    'claim-issue link',
    'OCR confidence',
    'manual confirmation',
    '원본성',
    '증거능력',
    '증명력',
    '제출본',
    '원본파일',
    '파생파일',
    '변경이력',
    '메타데이터',
    '진술서',
    '사실확인서',
    '반박서',
    '정보공개청구',
    '회신자료',
    '기록목록',
    '녹취록',
    '녹음파일',
    '캡처자료',
    '파일해시',
    '중복파일',
    '쟁점태그',
    '절차단계',
    '판단근거',
    '사실인정',
    '법률판단',
    '누락자료',
    '확인필요',
    '인용금지',
    '직접인용 가능',
    '수기검수',
    'OCR 오류',
    '원문대조 필요',
    '증거-주장 연결',
    '인용문맥',
    '접근권한',
    '검토메모',
    'Chain of Custody',
    'Redaction',
    'Redaction Log',
    'Relevance',
    'Materiality',
    'Admissibility',
    'Authentication',
    'Legal Hold',
    'Preservation Notice',
    'Review Protocol',
    'Issue Coding',
    'Chronology',
    'Access Log',
    'Audit Trail',
    'Hash Verification',
  ]),
}

const referenceTerms: Record<DeckId, ReadonlySet<string>> = {
  'ai-command': termSet([
    'Chain-of-Thought Prompting',
    'Zero-shot CoT',
    'Self-Consistency',
    'Least-to-Most Prompting',
    'Decomposed Prompting',
    'ReAct Prompting',
    'Tree of Thoughts',
    'Self-Refine',
    'Reflexion',
  ]),
  development: termSet([
    'Atomicity',
    'Consistency',
    'Isolation',
    'Durability',
    'Deadlock',
    'Mutex',
    'Primary Key',
    'Foreign Key',
    'Index',
    'Query Plan',
    'ACID',
    'Optimizer',
    'Referential Integrity',
    'SWE-bench',
  ]),
  'libraries-tools': termSet(['Hydration', 'SSR', 'Series', 'Prettier']),
  'joovis-architecture': termSet(['PWA', 'Cockpit', 'Term Card', 'Review Queue']),
  'dispute-integration': termSet([
    'Bates Number',
    'Privilege Review',
    'Foundation',
    'Custodian',
    'Production Set',
    'Native File',
    'Load File',
    'Near-Duplicate',
    'Threading',
    'Quality Control Sample',
    'Hot Document',
    'Source System',
    'Confidentiality Designation',
  ]),
}

const workingOverrides: Record<DeckId, ReadonlySet<string>> = {
  'ai-command': termSet([
    'Plan',
    'Context Compression',
    'Intent Framing',
    'Constraint Stack',
    'Decision Record',
    'Confidence',
    'Tradeoff',
    'Define the output contract',
    'Ask clarifying questions first',
    'Do not modify files yet',
    'List risks before implementation',
    'Give Korean explanation and English command',
    'Show the decision tradeoff',
    'Return a concise final report',
    'Delimiter Framing',
  ]),
  development: termSet([
    'Upstream',
    'Downstream',
    'Adapter',
    'Port',
    'Pipeline',
    'Orchestration',
    'Fixture',
    'Mock',
    'Stub',
    'Serialization',
    'Versioning',
    'Backward Compatibility',
    'Timeout',
    'Retry',
    'Cache',
    'Offline-first',
    'Happy Path',
    'Branch',
    'Merge Conflict',
    'Feature Flag',
    'Transition',
    'Transaction',
    'Parser',
    'Type Inference',
    'Type Narrowing',
    'Concurrency',
    'Race Condition',
    'Cache Invalidation',
    'Retry Policy',
    'Backoff',
    'Circuit Breaker',
    'Idempotency Key',
    'Event Loop',
    'Memory Leak',
  ]),
  'libraries-tools': termSet([
    'Context Provider',
    'Reducer',
    'Memoization',
    'Reconciliation',
    'Transpilation',
    'Tree Shaking',
    'Source Map',
    'Hot Module Replacement',
    'Semantic Versioning',
    'DataFrame',
    'SQL Query',
    'Lighthouse',
    'Accessibility',
    'Breaking Change',
    'Virtual DOM',
  ]),
  'joovis-architecture': termSet([
    'Truth Graph',
    'State Ledger',
    'Replay Harness',
    'Autopsy Trail',
    'Capability Matrix',
    'Golden Path',
    'Degraded Mode',
    'Drift Monitor',
  ]),
  'dispute-integration': termSet([
    '진술서',
    '사실확인서',
    '반박서',
    '정보공개청구',
    '회신자료',
    '녹취록',
    '녹음파일',
    '캡처자료',
    'Relevance',
    'Materiality',
    'Admissibility',
    'Authentication',
    'Legal Hold',
    'Preservation Notice',
    'Review Protocol',
    'Issue Coding',
    'Chronology',
    'Access Log',
  ]),
}

export function getTermCuration(term: CuratableTerm) {
  const deck = term.deck ?? inferDeck(term)
  const normalizedTerm = normalizeTerm(term.term)
  const explicitPriority = term.learningPriority
  const priority: LearningPriority =
    explicitPriority ??
    (referenceTerms[deck].has(normalizedTerm)
      ? 'reference'
      : workingOverrides[deck].has(normalizedTerm)
        ? 'working'
        : coreTerms[deck].has(normalizedTerm)
          ? 'core'
          : 'working')

  return {
    learningPriority: priority,
    selectionReason: term.selectionReason ?? getSelectionReason(priority),
  }
}

function getSelectionReason(priority: LearningPriority) {
  if (priority === 'core') {
    return '다른 개념을 이해하는 기반이거나 앞으로 반복해서 사용할 가능성이 높은 핵심 용어입니다.'
  }
  if (priority === 'reference') {
    return '특정 기술·연구·전문 절차에서 유용하지만 일상 반복 학습보다 필요할 때 찾아보는 편이 효율적입니다.'
  }
  return '실무에서 자주 만나며 핵심 개념을 실제 작업에 연결해 주는 확장 용어입니다.'
}

function inferDeck(term: CuratableTerm): DeckId {
  if (term.category === 'AI Command') {
    return 'ai-command'
  }
  if (term.category === 'JOOVIS-Specific') {
    return 'joovis-architecture'
  }
  return 'development'
}

function termSet(terms: string[]) {
  return new Set(terms.map(normalizeTerm))
}

function normalizeTerm(term: string) {
  return term.normalize('NFKC').toLocaleLowerCase('ko-KR').replace(/[^\p{L}\p{N}]+/gu, '')
}
